### ISSUE TITLE
Failed to create server profile with latest code from branch "server_profile"

### ISSUE THREAD

**Issue by SoibamRepo** [HewlettPackard/terraform-provider-oneview#107]
With latest codes, I am getting below errors 

var.oneview - *terraform.NodeRootVariable
var.server_profoneview_server_profile.test: Creating...
  hardware_name:  "" => "MXQ71906MB, bay 1"
  hardware_uri:   "" => "<computed>"
  ilo_ip:         "" => "<computed>"
  name:           "" => "terraform-test-0"
  public_mac:     "" => "<computed>"
  public_slot_id: "" => "<computed>"
  serial_number:  "" => "<computed>"
  template:       "" => "terraform-server-profile-template"
  type:           "" => "ServerProfileV9"
  uri:            "" => "<computed>"
oneview_server_profile.test: Still creating... (10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* oneview_server_profile.test: 1 error(s) occurred:

* oneview_server_profile.test: There must be at least 1 connection(s) configured to boot from the OS deployment network {"name":"DEPLOY", "uri":"/rest/ethernet-networks/2ca96de3-5449-4287-b6ee-4bb0caaacb3e"}.
Configure 1 connection(s) to boot from the OS deployment network {"name":"DEPLOY", "uri":"/rest/ethernet-networks/2ca96de3-5449-4287-b6ee-4bb0caaacb3e"}.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

2019/06/24 06:26:01 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-06-24T06:26:01.486-0500 [DEBUG] plugin.terraform-provider-oneview: 2019/06/24 06:26:01 [ERR] plugin: plugin server: accept unix /tmp/plugin990825157: use of closed network connection
2019-06-24T06:26:01.487-0500 [DEBUG] plugin: plugin process exited: path=/root/go/src/github.com/HewlettPackard/terraform-provider-oneview/terraform-provider-oneview
[root@localhost terraform-provider-oneview]# vim server_pro

Here is snapshot of SFT and terraform configuration 

![1](https://user-images.githubusercontent.com/26687825/60231832-42955c80-98b8-11e9-8738-3c3f09eb97d4.png)
![2](https://user-images.githubusercontent.com/26687825/60231851-4fb24b80-98b8-11e9-9888-b407531de305.png)

 

 

Server_profile.tf
provider "oneview" {
        ov_username = "${var.oneview["ov_username"]}"
        ov_password = "${var.oneview["ov_password"]}"
        ov_endpoint = "${var.oneview["ov_endpoint"]}"
        ov_sslverify = false
        ov_apiversion = "${var.oneview["ov_apiversion"]}"
        ov_ifmatch = "*"
}

resource "oneview_server_profile" "test" {
     count           = 1
     name            = "terraform-test-${count.index}"
     template = "terraform-server-profile-template"
     hardware_name        = "MXQ71906MB, bay 1"
     type = "ServerProfileV9"
   }

variable "oneview" {

    default = {
        ov_username = "xxxxxx"
        ov_password = "xxxxx"
        ov_endpoint = "https://10.188.x.x"
        ov_sslverify = false
        ov_apiversion = 800
    }
}

variable "server_profile" {

     default = {
         hardware_name = "MXQ71906MB, bay 1"
         template = "terraform-server-profile-template"
     }
}

**Comment by madhav-bharadwaj** [comment]
Hi @SoibamRepo , This feature is now added as part of this [PR](https://github.com/HewlettPackard/terraform-provider-oneview/pull/136). Please have a look at the example under example/demos folder to get more clarity.
