### ISSUE TITLE
mp_ip_address and mp_dns_name return NULL value

### ISSUE THREAD

**Issue by tdovan** [HewlettPackard/terraform-provider-oneview#118]
I'm trying to get/set the IPv4 of the SY480 iLO but it returned NULL value.

data "oneview_server_hardware" "server_hardware" {
             name = "Pod2_Rack15_Frame3, bay 6"
}
output "oneview_server_hardware_value" {
             value = "${data.oneview_server_hardware.server_hardware.mp_ip_address}"
}

**Comment by AsisBagga** [comment]
@tdovan Hi Tan, Thank you for raising the issue, this will be taken care in upcoming releases.
