### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/terraform-provider-oneview#12]
To make adoption easier, I think it would be good to have some more detailed documentation with plenty of examples and step-by-step instructions to get going. If we can get the docs put onto the Terraform website, that would be great too, but let's get them into the state that we want them first :)

Possible examples to include:
- Basic OV resources (e.g., Ethernet Networks)
- Slightly more complex resources (e.g., Server Profile Templates)
- Complete provisioning example (including Profile from Template OS build plan, and CM tool)

**Comment by mbfrahry** [comment]
Handling this now
