### ISSUE TITLE
Broken link at endpoints-support.md

### ISSUE THREAD

**Issue by Baykonur** [HewlettPackard/terraform-provider-oneview#121]
The link: [HPE OneView REST API Documentation](http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.1/cic-api/en/api-docs/current/index.html) is broken at [endpoints-support page](https://github.com/HewlettPackard/terraform-provider-oneview/blob/master/endpoints-support.md)

**Comment by soodpr** [comment]
@Baykonur - Thanks for pointing out this. We will update this to http://h17007.www1.hpe.com/docs/enterprise/servers/oneview4.1/cicf-api/en/index.html#

**Comment by madhav-bharadwaj** [comment]
Updated this in this PR: https://github.com/HewlettPackard/oneview-golang/pull/179
