### ISSUE TITLE
plug-in directory as instructed in README.md

### ISSUE THREAD

**Issue by mpolski** [HewlettPackard/terraform-provider-oneview#139]
The instrustions may be confusing for some.

> $ mv $GOPATH/bin/terraform-provider-oneview /usr/local/bin/terraform

will in fact replace terraform executable on some systems (e.g. Ubuntu, when terraform is installed manually), the plug-in should go into:
~/.terraform.d/plugins/linux_amd64/

**Comment by AsisBagga** [comment]
@mpolski Hi, Thanks for pointing this out, will have this included in our next release. Thank you.

**Comment by AsisBagga** [comment]
@mpolski Hi, If you have other query or suggestion feel free to open a new issue, for now ill be closing this issue since we will make updates after our coming release. Thanks.
