### ISSUE TITLE
Missing helm chart deployment package

### ISSUE THREAD

**Issue by kpetsev** [HewlettPackard/terraform-provider-oneview#161]
In stage & production environments my customers use helm chart* (yaml based) for deploying containerised application (* https://kubernetes.io/docs/reference/tools/#helm) 

Could you create a helm chart deployment package for the provider in order to be aligned with the validation requirements for production usage that my customers have?

**Comment by nabhajit-ray** [comment]
We have added this our backlog and will be taken up as per our priority . Closing this here.
