### ISSUE TITLE
Logical Interconnect Group dependentResourceUri error

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#162]
I'm seeing the following error trying to use some existing Terraform code and state since upgrading to OneView 5.0.  I have updated to the latest version of the OneView plugin and changed to API version 1200 (from 600) and I am still seeing it.

```
	* module.c7000-FF10.oneview_logical_interconnect_group.ligA: 1 error occurred:
	* oneview_logical_interconnect_group.ligA: The field dependentResourceUri was either omitted or set to null.  Please use a value. 
```

```
	* module.Synergy.oneview_logical_interconnect_group.ligA: 1 error occurred:
	* oneview_logical_interconnect_group.ligA: The field dependentResourceUri was either omitted or set to null.  Please use a value. 
```

According to the API documentation, this field is read-only so I am super confused at this point.

**Comment by AsisBagga** [comment]
@adarobin Hi Adam, Thanks for pointing out the issue, this has been fixed in OneView Terraform SDK Release v1.5.0
Ill proceed with closing this issue, if you have any concerns or doubts, you may open a new issue. Thank you.
