### ISSUE TITLE
terraform import oneview_server_profile_template missing settings

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#233]
I had a look at the configuration here:
https://github.com/HewlettPackard/terraform-provider-oneview/blob/master/examples/demos/infrastructure_provisioning_with_i3s.tf

I tried to import a server profile template into my state file, that has bios_options, boot, local storage, etc and
only these attributes came in via import: 
```
"affinity"
"boot_order.#"
"enclosure_group"
"etag"
"hide_unused_flex_nics"
"id"
"mac_type"
"name"
"serial_number_type"
"server_hardware_type"
"type"
"uri"
"wwn_type"
```
Is this something that can be addressed?  We are about to embark on a huge Synergy migration, and all the "important" template settings aren't getting imported.  Let me know if you need addtional info.

ref REST API v1000

**Comment by rismoney** [comment]
Another point on similar topic- 

When I import a server profile, `import "oneview_server_profile.myprofilename myprofilename" . it does not import the template identity that is associated with that template.   This too is problematic as there is an obvious association here that needs to be preserved.

**Comment by nabhajit-ray** [comment]
Hi Rismoney ,

Can you share which  server profile template settings you are looking for?

**Comment by rismoney** [comment]
The 2 I need are bios settings and local storage, which is a raid1 array.

**Comment by rismoney** [comment]
I have a question regarding passing bios settings in.  Since this provider only currently supports .11 of Terraform, how do you pass in:
```terraform
bios_option = {
     overridden_settings = ["${var.overridden_settings}"]
     manage_bios = true
}

variable "overridden_settings" {
  type = "list"
  default =[
    { 
      id = "TimeZone"
      value = "Unspecified"
    },
    { id = "MinProcIdlePkgState"
      value = "NoState"
    }
]
}
```

**Comment by rismoney** [comment]
i had a separate issue opened.  can network connections also be added?
