### ISSUE TITLE
local storage configuration

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#234]
how would i configure the following in a server profile template:
Integrated storage controller
Mode Managed by OneView
Write cache Managed manually

Name | Type | RAID Level | Number of Drives | Size GB | Drive Technology | Boot | Accelerator
-- | -- | -- | -- | -- | -- | -- | --
OS | Logical drive | RAID 1 | 2 | n/a | not specified | Yes | Managed manually

**Comment by rismoney** [comment]
this doesn't seem to work-

```
  local_storage = {
    complianceControl = "Checked"
    controllers = {
      deviceSlot = "Embedded"
      initialize = false
      logicalDrives = [ { 
        name = "OS"
        
        numPhysicalDrives = 2
        raidLevel = "RAID1"
        accelerator = "Unmanaged"
      } ]
      mode = "Mixed"
    }
  }
```

**Comment by rismoney** [comment]
I'm not understanding how the associated config goes in terraform based on this:
ref https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cic-api/en/index.html#rest/server-profile-templates

**Comment by AsisBagga** [comment]
@rismoney Hi Rich, Thank you for raising this issue. As of now, our Terraform Provider SDK scope's limited to few attributes for local storage while creating server profile template, However, I'll be adding this enhancement and will keep you posted on this.
