### ISSUE TITLE
Building the docker container -- do you need all the extra overhead of the OS?

### ISSUE THREAD

**Issue by patrickdappollonio** [HewlettPackard/terraform-provider-oneview#24]
Hello!

So given the conversation about docker, we can reduce the docker container to be only up to the filesize of `terraform-provider-oneview` and `terraform` binaries together, rather than having a full OS. You can still run terraform and other stuff in there, it's just that it won't have the extra overhead.

We can achieve this by compiling the binary externally, by static-linking it, then download the terraform, and together put them in a docker container based on the [CenturyLink `ca-certs` docker container](https://hub.docker.com/r/centurylink/ca-certs/) (which is the scratch container plus the default SSL certificate chain to allow SSL communication).

By doing so, the docker image should be less than 50 MB size and it will just contain one or two layers, making it lightweight and portable.

We can use a Makefile or a Bash script to automate the build process of the image itself (which will consist of downloading terraform, then building statically then create the docker container off of `ca-certs`) to ease the process.

Now this also may be overkilling if there's no direct need of a small, lightweight docker container either, so I'm labeling it as "enhancement".

Post your thoughts below!

**Comment by patrickdappollonio** [comment]
Pinging @jsmartt for his thoughts too.

**Comment by thebsdbox** [comment]
You don't necessarily need to static compile them, just do the volume mapping `-v /lib64:/lib64:ro` the main dependancy will be libc when using the container. If you're really on a mission to shrink the binaries then you can use the `upx` tool to compress the binaries further :-)

**Comment by patrickdappollonio** [comment]
I agree, but the goal would be to use a Docker image clean enough and lean enough so you can use scratch with them. Plus, we're already statically compiling it inside the container, so I was proposing moving that process outside and then just move the resulting binary in, so you don't need the overall stack inside the container.

Plus, it's recommended in the Go community rather than volume-map it. :-)

**Comment by wenlock** [comment]
I like it, but how about a `Dockerfile.cli` file that specifically focuses on the pushed results, and pulls it from a `Dockerfile.build` which would have all dependencies dealing with building from sources for at least the oneview plugin side (toss the terraform binaries part if it's not used in testing, or make a `Dockerfile.testing` that would focus on that).   What do you think?

**Comment by wenlock** [comment]
My other thought is that if you make a `Dockerfile.cli` then we can start introducing specific entrypoint.sh scripts that help automate usage of the plugin in the context of terraform for oneview, and making it super easy to consume via cli calls.

**Comment by patrickdappollonio** [comment]
So I talked with the DCIA team here and it could be good to have a Dockerfile per "flow", but the most asked question was: What's the use case of a Docker container here? Maybe all you need is just the binary file along with terraform and we can provide a way to have a zip file with both (terraform and terraform-provider-oneview) after a successful merge.

If there's need for a docker Image with terraform and our provider, then they all agreed that maybe having a "scratch"-only is just overengineering a solution where simplicity is better. Same was said for having 3 different Dockerfiles.

Additionally, having a Dockerfile with a bash entrypoint will fail under a Docker scratch image, since it won't contain bash (it won't contain anything but just the two binaries) so it will still need the Alpine base (even when we can still remove the Go stack from the image).

So I see two options (in the lack of better ones): 

a) We can keep the current Docker image which is already simple to follow and easy to use; or 
b) We can add the multiple, different Docker images where the first one will be `build` and it will be shared in the Docker Hub, which will be [like the `hello-world` one](https://github.com/docker-library/hello-world/blob/bdee60d7ff6b98037657dc34a10e9ca4ffd6785f/hello-world/Dockerfile) where you just have the two binaries (terraform and terraform-provider-oneview); the second one being the CLI one for you guys, which can still be Alpine + Go image and the testing one we can probably omit it.

If you think the extra complexity allows for the option b) to happen, then I'll be happy to set it up!

**Comment by wenlock** [comment]
I like the scratch image idea, and the cli one can come later, no need to do it now... However, I like keeping it simple to. In fact, I'm already using it internally.  Let me send you the PR where I'm starting to consume it.

**Comment by patrickdappollonio** [comment]
I'm closing this in the meantime. We can reopen it if we see fit. Thanks everyone!
