### ISSUE TITLE
Enhancement: Publish to Terraform Registry

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#258]
It would be great if this provider were available on [registry.terraform.io](https://registry.terraform.io/). This is probably blocked by #62 (since 0.11 doesn't support the registry anyways).

More info at:
https://www.terraform.io/docs/registry/providers/publishing.html
https://www.terraform.io/guides/terraform-provider-development-program.html

**Comment by nabhajit-ray** [comment]
Hi Adam,

We are upgrading our sdk to support the plugin SDK and  validating with terraform 0.12.29. Publishing to registry will be done after that.

**Comment by rismoney** [comment]
What is the state of the terraform .12 branch?   Should I be using that or the master which is .11?

**Comment by nabhajit-ray** [comment]
> What is the state of the terraform .12 branch? Should I be using that or the master which is .11?

We have added a branch named Terraform-0.12 . If you want to run your configuration files using Terraform 0.12 binary please checkout that branch and run your *.tf files. Do follow the README specific to Terraform-0.12 branch. You can also check the wiki section .Do let us know if it is working for you

**Comment by nabhajit-ray** [comment]
Closing this  since provider is now available at registry.
https://registry.terraform.io/providers/HewlettPackard/oneview/latest?pollNotifications=true
