### ISSUE TITLE
local_storage not working as expected

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#267]
#234 added local storage capability.  This works partially

```  local_storage = {
      controller = [{
        device_slot =  "Embedded"
        drive_write_cache = "Unmanaged"
        initialize = true
        mode = "Mixed"
        predictive_spare_rebuild = "Unmanaged"
        logical_drives = [{
          accelerator = "Unmanaged"
          bootable = "true"
          # drive_technology = "SasHdd"
          name = "TestLd"
          num_physical_drives = 2
          raid_level = "RAID1"
        }]
      }]
    }
```

The above works when initialize is true but not when initialize = false.

when false:

1 error occurred:
        * module.spt_g10_trading_eg4_rsiegelTest.oneview_server_profile_template.spt: 1 error occurred:
        * oneview_server_profile_template.spt: Error in response: An unexpected error occurred.
 Response Status: 400 Bad Request
 Response Details: An unexpected and unhandled runtime exception occurred.

@AsisBagga @nabhajit-ray

**Comment by rismoney** [comment]
i think this works. closing - will re-open if needed after further testing.

**Comment by rismoney** [comment]
It does not work consistently.  not sure why - not a lot of insight from debug log.  Also, less important to my use case,  a subsequent change from true->false does not work.

**Comment by rismoney** [comment]
import_configuration does need seem like it works either.

**Comment by AsisBagga** [comment]
@rismoney Hi, passing false value for a Boolean Attribute is a bug with terraform 0.11 core, basically the Legacy Terraform SDK has no way to distinguish unset and zero values. 
Anyway, I have implemented a work around which works perfectly fine now, I have raised the PR, maybe you can clone it, do a build and test it.

And for import configuration, will raise a separate issue.

**Comment by AsisBagga** [comment]
Since this issue is addressed ill proceed to close this issue. 
For Import Configuration I've opened a new issue.
