### ISSUE TITLE
local storage issue ( defined in server profile template)

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#268]
I have local storage defined in a server profile template (a raid 1, 2 drive)

When I create a server profile from that template, the logical disk configuration is missing from the profile.

All this profile functionality, is becoming critical to our organization as we are about to do a huge migration.
Is there a way to expedite this functionality?  Can I open cases directly with HPE? 

Thank!
@AsisBagga @nabhajit-ray

**Comment by AsisBagga** [comment]
@rismoney Hi, Thanks for raising this issue. This is issue is also fixed under PR 269.

**Comment by AsisBagga** [comment]
@rismoney Hi Rich, Since this issue is addressed in our PR and is merged, ill go ahead and close this. 
For any other query please open a new issue, will be glad to assist you.
