### ISSUE TITLE
more server profile/template issues not working as expected

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#272]
if I create a server profile template with local storage or bios settings terraform properly creates it.
but if I go into the GUI and modify a storage/bios setting and then re-run the plan terraform should re-evaluate the actual configuration and report the settings drift.  A subsequent terraform apply should remediate the drift either through modifying the resource attributes, or forcing a new resource (delete/recreate)

This does not seem to happen and terraform reports back no changes as if the above process is not working as expected.

Let me know if there is anything else you need.

@AsisBagga @nabhajit-ray

**Comment by nabhajit-ray** [comment]
Thanks for raising this. Let me check and get back to you

**Comment by AsisBagga** [comment]
@rismoney Hi Rich, this issue has been addressed and will be reflecting in our upcoming release soon.

**Comment by AsisBagga** [comment]
Since this issue is addressed we will be proceeding with closing it, if you encounter any other issue please feel free to open a new issue. Thank you.
