### ISSUE TITLE
local storage configuration for profiles - importConfiguration

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#280]
Is it possible to add this rest api attribute to TF:

importConfiguration
https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/server-profiles

This boolean value allows you to import disks of existing blades when creating profile.

@AsisBagga Thank you for your assistance in this and all the other issues!

**Comment by AsisBagga** [comment]
@rismoney Hi Rich, You're welcome and thank you as well for raising this issues. 

However, when i refer the link it takes to me to Oneview REST API Guide, do you have any specific attribute for your import requirement for server profile resource?

**Comment by rismoney** [comment]
I don't think so - I think it's just a boolean for importConfiguration and initialize

The specific combination I believe I need would be 
Enable "Import existing logical drives"
Disable "Re-initialize controller on next profile application"

The idea being if create the profiles on existing servers, I do not want to wipe the existing RAID arrays.  In our module move to new enclosure project these settings are key to have.

**Comment by AsisBagga** [comment]
@rismoney sure, thank you Rich, we will add this as an enhancement for adding initialize and importConifiguration attributes for server profile and server profile template.

**Comment by AsisBagga** [comment]
Since this feature is added, we will be proceeding with closing this issue. If you have any concern you may open a new issue and we will address it, Thank you.
