### ISSUE TITLE
Adding Synergy Enclosures

### ISSUE THREAD

**Issue by wayno123** [HewlettPackard/terraform-provider-oneview#282]
Can you help me with a Terraform problem that I can't quite figure out? I'm not sure if I'm doing something wrong or there is a bug that I can't fix.

**OneView 5.40     on DCS simulator
Terraform 12.30
Terraform-provider-oneview-6.0.0-12**
 

```
variable "enc_name1" {

 type =             string

 description = "Enclosure name"

 default =        "0000A66101"

}

resource "oneview_enclosure" "enclosure-1" {

    name =                           var.enc_name1

    licensing_intent =           "OneView"

    enclosure_group_uri=    "/rest/enclosure-groups/679a4c10-87a2-4069-8956-bf03ca79eacc"

}

```
 

Getting error message(s) when I run the "terraform apply":

**Error: Error in response: Invalid JSON type.

 Response Status: 400 Bad Request

 Response Details: The "type" field content, "unknown", included in this request is not valid.**

 
I don't think the "type" is expecting:

       type                   = "EnclosureV8"

because I tried that. I can't figure out problem with the json type.

Let me know if you require additional outputs or settings. Thanks.

**Comment by wayno123** [comment]
Updates please. Are we working on this issue? Thanks.

**Comment by AsisBagga** [comment]
@wayno123 Thank you for raising the issue. 
I'll test this in lab today and will let you know.

**Comment by AsisBagga** [comment]
@wayno123 Hi, looking at your HCL code,  I hope you didn't missed to provide the hostname, it is the link-local IPv6 address of the enclosure's frame link module, you will need to provide it inorder to add remote enclosure. 

```
resource "oneview_enclosure" "enclosure_inst" {
	enclosure_group_uri = "${data.oneview_enclosure_group.enclosure_group.uri}"
	host_name = "${var.en_hostname}"
	licensing_intent = "Oneview"
	name = "Test Enclosure"
}
```

**Comment by wayno123** [comment]
Thank you for your response.
I added the missing host_name value and my terraform apply command seemed to work. Thanks.
variable "enc_hostname1" {
 type            = string
 description = "IP address of FLM"
 default       = "fe80::2:0:9:1%eth2"
}
resource "oneview_enclosure" "enclosure-1" {
    host_name =             var.enc_hostname1
    name     =                  var.enc_name1
    licensing_intent =      "OneView"
    enclosure_group_uri=    "/rest/enclosure-groups/679a4c10-87a2-4069-8956-bf03ca79eacc"
}
Question:   is there a "data" command to run to identify the IPv6 Link-Local address for the FLM in the enclosure? I could not find one, but I'm new to testing Terraform. I had to search deeply in the OneView GUI to find that Management IP address.

**Comment by wayno123** [comment]
I believe there is still a problem with the code. It does not seem to be idempotent. After successfully adding my enclosures, the next time I ran a "terraform apply", I got the same JSON messages as before. Somehow, the code is finding he existing resource in the state file and not being able to overlook it and move on.

```
oneview_enclosure.enclosure-1: Modifying... [id=0000A66101]
oneview_enclosure.enclosure-2: Modifying... [id=0000A66102]
oneview_enclosure.enclosure-3: Modifying... [id=0000A66103]

Error: Error in response: Invalid JSON type.
 Response Status: 400 Bad Request
 Response Details: The "type" field content, "unknown", included in this request is not valid.

  on main.tf line 175, in resource "oneview_enclosure" "enclosure-1":
 175: resource "oneview_enclosure" "enclosure-1" {

Error: Error in response: Invalid JSON type.
 Response Status: 400 Bad Request
 Response Details: The "type" field content, "unknown", included in this request is not valid.

```
  on main.tf line 182, in resource "oneview_enclosure" "enclosure-2":
 182: resource "oneview_enclosure" "enclosure-2" {

Error: Error in response: Invalid JSON type.
 Response Status: 400 Bad Request
 Response Details: The "type" field content, "unknown", included in this request is not valid.

  on main.tf line 189, in resource "oneview_enclosure" "enclosure-3":
 189: resource "oneview_enclosure" "enclosure-3" {
```

What do you think? Am I doing something wrong in my code?
I've noticed this same behavior with adding networks. Randomly I will get an error message about an existing network. I can open a separate issue for this if needed.
Thanks.

**Comment by AsisBagga** [comment]
@wayno123 Hi, we are aware of the inconsistency within the provider for idempotency and we are continuously working to enhance this SDK. However, this bug for adding same enclosure multiple time should ignore for next apply/plan has been implemented and this will be reflecting in our coming release soon.

**Comment by AsisBagga** [comment]
Since this enhancement is addressed will proceed with closing this issue.
