### ISSUE TITLE
Error updating logical interconnect group Synergy OneView 5.5

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#289]
I'm getting this error in a Synergy environment with OneView 5.5 and provider version 1.7.0-12 trying to update an existing logical interconnect group.

```
Error: Error in response: Unrecognized JSON field.
 Response Status: 400 Bad Request
 Response Details: The field named portFlapProtection near line 1, column 1,659 is not a valid field in this JSON object.

  on .terraform/modules/miserver-eth-ligs-unstacked/main.tf line 1, in resource "oneview_logical_interconnect_group" "ligA":
   1: resource "oneview_logical_interconnect_group" "ligA" {
```

**Comment by nabhajit-ray** [comment]
Thanks  Adarobin. We will look into this.

**Comment by wayno123** [comment]
I think I've run into that before. It is complaining about not being Idempotent. In the past, if I've "tainted" that resource, and rebuild it with an apply, it seems to work. See if this works for you.

**Comment by adarobin** [comment]
@wayno123 This is a Logical Interconnect Group in use in production by Logical Interconnects so deleting and recreating it is not an option.  I did try `terraform state rm` and `terraform import` on it but that did not make a difference.

**Comment by AsisBagga** [comment]
This issue is fixed and merged to the master branch, and will be seen in the upcoming release.
