### ISSUE TITLE
Enhancement: Add Description and Bios settings to server template

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#29]
Hi,

Just looking at the wiki for the options on this and it would be great if your able to add the description and BIOS settings to the server template.

Cheers

Details:
wiki url - https://github.com/HewlettPackard/terraform-provider-oneview/blob/master/docs/r/server_profile_template.html.markdown

Add Bios Settings/Description options which are currently in the templates in the UI.

**Comment by AsisBagga** [comment]
@wingZero21 Thanks for letting us know, a new PR is submit for same. This issue will be addressed in upcoming releases.
