### ISSUE TITLE
server profile template

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#294]
I just upgraded to api 2600.

I am trying to create a server profile template:

I am getting this error:

```
Error: Error in response: Invalid JSON type.
 Response Status: 400 Bad Request
 Response Details: The "type" field content, "ServerProfileTemplateV6", included in this request is not valid.
```

relevant config:

```
resource "oneview_server_profile_template" "spt" {
  name                      = var.spt_name
  type                      = var.profile_type
  enclosure_group           = var.enclosure_group
  server_hardware_type      = var.server_hardware_type
  mac_type                  = "Physical"
  wwn_type                  = "Physical"
  serial_number_type        = "Physical"
  boot_order                = ["HardDisk"]
  boot_mode {
    manage_mode = true
    mode = "UEFI"
    pxe_boot_policy = "Auto"
  }
}

variable "profile_type" {
  description = "The profile type to be created."
  default = "ServerProfileTemplateV6"
}
```

**Comment by rismoney** [comment]
@AsisBagga is this something you can assist with?  We have HP onsite and would like to get this going.   Not sure how we can escalate.

**Comment by AsisBagga** [comment]
@rismoney i think you are providing wrong TemplateType, with v2600 it should be ServerProfileTemplateV8.

**Comment by rismoney** [comment]
That was it!  Thanks for the rapid reply!  Is that documented somewhere?

**Comment by AsisBagga** [comment]
> That was it! Thanks for the rapid reply! Is that documented somewhere?

You're welcome Rich. Yes, In the OneView Dashboard under help section you have REST API Reference Guide, inside it you can find ServerProfileTemplate Resource's POST operation, there its all documented.
