### ISSUE TITLE
Query on syntax for adding boot order for server template

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#30]
Hi,

Looking at adding boot order on a server template however noticed that it does not seem to specify on the wiki how this would look once its been added.

Can you update to the wiki to advise how the boot options need to be specified in the parameters.

eg 1= harddisk 2=PXE etc

Cheers

Details:
wiki page - https://github.com/HewlettPackard/terraform-provider-oneview/blob/master/docs/r/server_profile_template.html.markdown

```
eg:

resource "oneview_server_profile_template" "default" {
  name = "test-template"
  enclosure_group = "none"
  server_hardware_type = "DL380 Gen9 1"
  description = "Base Server Profile with Legacy bios boot and Max Performance settings"
  boot_order = "??"

boot_order- (Optional) Defines the order in which boot will be attempted on the available devices. Different hardware take different boot orders.

```

**Comment by wingZero21** [comment]
Hi,

Is there any chance of getting the wiki updated for an example of setting this option?

Cheers

**Comment by wingZero21** [comment]
Hi,

As above, is there any chance of getting some information on how the boot order parameters are required to be set using terraform?

Cheers

**Comment by jsmartt** [comment]
@wingZero21, the documentation for the API says it accepts an array of strings (e.g. `["PXE", "HardDisk", "CD", "Floppy", "USB"]` ). From the looks of the [code](https://github.com/HewlettPackard/terraform-provider-oneview/blob/a491f7efb3d205b74998c9a66c861d26b898024d/oneview/resource_server_profile_template.go#L35-#L39), it looks like it's the same in Terraform.

If you can confirm the functionality, I'll update the docs 😃

**Comment by wingZero21** [comment]
Hi,

I have added this as you mentioned but I believe because there is not currently an option to also select the boot mode (legacy bios/uefi) it is not actually applying it as expected. 

I am not seeing any errors during the apply, however when checking the profile its not showing specifically that the boot order has been assigned and when booting a server it does not seem to be on that specific order that was set.

Cheers

**Comment by jsmartt** [comment]
It does seem to be missing the boot mode property, but I would hope it would at least set the order correctly...

**Comment by AsisBagga** [comment]
Hi, @wingZero21 @jsmartt 
Boot mode is supported in server profile template.
Let me know if you have any queries before we close the issue.

**Comment by AsisBagga** [comment]
Hi, Since we haven't received any updates, ill proceed with closing this issue.
If you still have any query, you can let us know by opening a new issue, we will be glad to assist. Thanks.
