### ISSUE TITLE
Can't create resource oneview_server_profile

### ISSUE THREAD

**Issue by Schluggi** [HewlettPackard/terraform-provider-oneview#301]
Hello,

after #300 I have manually created an almost empty server profile template.
Now I want to create a profile based on this template:

```tf
resource "oneview_server_profile" "server_profile" {
  name = "TEST"
  template = "DL360p Gen8 1 legacy"
}
```
I got an error: `Response Details: The "type" field content, "ServerProfileV9", included in this request is not valid.`
1. Where can i find the right `type` for my oneview instance? 
2. [The doc](https://github.com/HewlettPackard/terraform-provider-oneview/blob/master/docs/r/server_profile.html.markdown) seems to be wrong. As described there, the default value for `type` should be `ServerProfileV5` not `ServerProfileV9`.
3. But in [the example](https://github.com/HewlettPackard/terraform-provider-oneview/blob/master/examples/server_profiles/main.tf) the type is `ServerProfileV12`.

So i tried every Profile version and `ServerProfileV12` seems to work fine.

```tf
resource "oneview_server_profile" "server_profile" {
  name = "TEST"
  template = "DL360p Gen8 1 legacy"
  type = "ServerProfileV12"
}
```
Now i got this message: `Error: The value specified for the profile MAC assignment type is not valid or not supported.`
After analyzing the post request from the web interface, I noticed that the default values of `wwn_type`, `mac_type` and `serial_number_type` are different. Via the web interface they are all set to `Physical` and via Terraform the default values are always `Virtual`. It would be helpful to have the same defaults everywhere. 

So i define them:
```tf
resource "oneview_server_profile" "server_profile" {
  name = "TEST"
  template = "DL360p Gen8 1 legacy"
  type = "ServerProfileV12"
  serial_number_type = "Physical"
  wwn_type = "Physical"
  mac_type = "Physical"
}
```
And... yes, another one: `Error: Profile affinity is applicable only for blade servers. Specify null affinity for rack servers.`
But this error is not fixable for me. 
If i set `affinity = null` as the error message said, terraform will use the default value which is `bay`. So it doesn't matter if i specify the affinity and set it to `null`, or leave it out. In other words: I cant change the the affinity. 
I also tried the option `BayAndServer` listed in the [restful api docs](https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/server-profiles), but the error remains.

Using terraform 0.15.1 and OneView 6.00.00.

**Comment by AsisBagga** [comment]
Since this issue is fixed. Proceeding with closing it.
