### ISSUE TITLE
using provider locally or the registry not working?

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#304]
is there a way to tell terraform 13+ to use a provider built off a branch locally (on a windows node)
previously I could go build off a branch locally, and copy the .exe to the terraform.exe directory and run it.
I believe the below will fetch the provider from the registry.
Apparently I can't do source ="path/to/exe" or maybe I am doing it wrong.

```
terraform {
  required_providers {
    oneview = {
      source = "HewlettPackard/oneview"
    }
  }
```

**Comment by nabhajit-ray** [comment]
Hi Rismoney,

You can try creating below directory in your workspace
PS> pwd
C:\Users\terraform-provider-oneview
PS>mdkir -p  .terraform\plugins\registry.terraform.io\hewlettpackard\oneview\6.1.0-13\windows_amd64\

And copy the exe in that path.

PS >ls  .terraform\plugins\registry.terraform.io\hewlettpackard\oneview\6.1.0-13\windows_amd64\


Mode                LastWriteTime         Length Name
-a----        5/12/2021   9:58 PM       23028736 terraform-provider-oneview_v6.1.0-13.exe

Let me know if that helps

**Comment by nabhajit-ray** [comment]
Closing this as of now. Feel free to reopen if you still need some help
