### ISSUE TITLE
[feature request] resources server_hardware & server_hardware_type

### ISSUE THREAD

**Issue by Schluggi** [HewlettPackard/terraform-provider-oneview#309]
Hi,

at this moment the Terraform resources server_hardware and server_hardware_type are missing. The data parts are already there.
It would be nice to have the missing parts.

**Comment by nabhajit-ray** [comment]
Thanks @Schluggi . We will look into this,

**Comment by nabhajit-ray** [comment]
Server Hardware support is there in out master branch . Server hardware type support is added to our backlog and will picked up as per our priority list. Closing it here.
