### ISSUE TITLE
Enhancement: Add notification alert filter configuration

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#31]
Hi,

It would also be great if we were able to add the settings to create the alert filters on oneview through the provider.

Potentially something like the below example.

```
resource "oneview_notification_alert_filter" "default" {
  name = "test-server-profile-template"
  alert_email = "Enabled"
  alert_criteria = "Advanced"
  alert_filter = "Critical"
  resource_scope = "Match any"
  email_address= "youremail@email.co.uk"
}
```

**Comment by patrickdappollonio** [comment]
Hello @wingZero21,

Currently, the `oneview-sdk-go` doesn't support notifications. Once that functionality lands on [`oneview-golang`](https://github.com/HewlettPackard/oneview-golang) then we can implement it here.

Pingin @wenlock for more insight.

**Comment by wenlock** [comment]
@patrickdappollonio I started the issue over [here](https://github.com/HewlettPackard/oneview-golang/issues/104). Hoping it can start unlocking that capability and identifying the use cases an interest.  We might have some of this around InfraKit integration as well, but I believe its a bit far out for us still.

**Comment by patrickdappollonio** [comment]
Agreed, from an automation perspective I think there's other things in the backlog still way above email notifications. I'll take a second look and depending on how things go I may provide a PR for `oneview-golang`. Thanks @wenlock!

**Comment by nabhajit-ray** [comment]
We have added this our backlog and will be taken up as per our priority . Closing this here.
