### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by rejivl** [HewlettPackard/terraform-provider-oneview#329]
I am getting this error when trying to create server profile. This occurs when executing "Terraform apply". I am using the container environment to execute the script. 

`/go/src/github.com/HewlettPackard/terraform-provider-oneview # terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # oneview_server_profile.default will be created
  + resource "oneview_server_profile" "default" {
      + affinity              = "Bay"
      + hardware_name         = "SGH831YR9H, bay 7"
      + hardware_uri          = (known after apply)
      + hide_unused_flex_nics = true
      + id                    = (known after apply)
      + ilo_ip                = (known after apply)
      + mac_type              = "Virtual"
      + name                  = "TerraformSP"
      + public_mac            = (known after apply)
      + public_slot_id        = (known after apply)
      + serial_number         = (known after apply)
      + serial_number_type    = "Virtual"
      + type                  = "ServerProfileV10"
      + uri                   = (known after apply)
      + wwn_type              = "Virtual"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Warning: Interpolation-only expressions are deprecated

  on main.tf line 2, in provider "oneview":
   2: 	ov_username  = "${var.username}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 3 more similar warnings elsewhere)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

oneview_server_profile.default: Creating...

**Error: rpc error: code = Unavailable desc = transport is closing**

/go/src/github.com/HewlettPackard/terraform-provider-oneview # 

`

**Comment by AsisBagga** [comment]
Hi @rejivl, Please let me know the following:-
1. What's the terraform version 
2. Which docker image are you using?
3. Can you check if you're able to reach oneview from the docker? try pinging.
4. Can you share the configuration file please?

**Comment by rejivl** [comment]
Hi Asis, please find below the details you have requested :

 1. What's the terraform version  ---> **Terraform v0.13.6**
 
![image](https://user-images.githubusercontent.com/40034993/121470158-64bc1280-c9db-11eb-9ab2-361886ff0191.png)


 2. Which docker image are you using?  --> **docker.io/hewlettpackardenterprise/hpe-oneview-sdk-for-terraform (v6.1.0-13-OV6.1)**

![image](https://user-images.githubusercontent.com/40034993/121470117-52da6f80-c9db-11eb-8bef-d6ece3dc94d3.png)
 

3. Can you check if you're able to reach oneview from the docker? try pinging.   ---> **Yes, I am able to ping Oneview.**

![image](https://user-images.githubusercontent.com/40034993/121470229-87e6c200-c9db-11eb-9bf8-72ca7ed35eba.png)


4. Can you share the configuration file please?  ---> **Need help with gathering this info. Could not understand which configuration file you are looking for.**

**Comment by rejivl** [comment]
Some additional info: 
When enabling the trace log for terrform , got the below details. 

![image](https://user-images.githubusercontent.com/40034993/121471378-32abb000-c9dd-11eb-9fa6-bb571a68230f.png)

**Comment by rejivl** [comment]
Thanks Asis for the support
After changing the scope and using the  privileged user credentials this issue is resolved. 
I was able to add a test server profile.

**Comment by nmukkelli** [comment]
@rejivl, @AsisBagga 
I'm facing the same error, could you pls let me know how did you resolve in bit more detail pls?
Trying to figure out what you mean by "After changing the scope and using the privileged user credentials this issue is resolved."

I'm already using admin credentials, what do you mean by 'scope'?

I'm using 
Terraform v1.0.0 on linux_amd64 and
terraform-provider-oneview_v6.1.0-13

I'm getting the error when I did a 'terraform plan'

Here is the error message:
[terraform-plan-output.txt](https://github.com/HewlettPackard/terraform-provider-oneview/files/6745464/terraform-plan-output.txt)

Would be great if you guys can help me out here.
