### ISSUE TITLE
Terraform crash creating Server Profile Template

### ISSUE THREAD

**Issue by wayno123** [HewlettPackard/terraform-provider-oneview#336]
I've been working on creating a new Server Profile Template. It's been working well until today when I started including "boot" items in the resource. Terraform 0.13. OneView 6.10. REST API 2600.

I was trying to isolate the issue by commenting in/out sections of the resource. I think the problem is within the boot section. Problem/crash only happens in the "apply" command. "Plan" completes successfully. 

`  boot {
        manage_boot        = var.boot_options.manage_boot_order
        boot_order         = var.boot_options.boot_order
  }
  # boot_mode {
  #       manage_mode        = var.boot_options.manage_boot_settings
  #       mode               = var.boot_options.boot_mode_selected
  #       pxe_boot_policy    = var.boot_options.pxe_boot_policy
  # }`

I'll attach the crash log, my main.tf, variables.tf, and variables.tfvars.

I use the command "terraform apply -var-file="variables.tfvars"
[terraform.tfstate.txt](https://github.com/HewlettPackard/terraform-provider-oneview/files/6678447/terraform.tfstate.txt)

[variables.tfvars.txt](https://github.com/HewlettPackard/terraform-provider-oneview/files/6678435/variables.tfvars.txt)
[crash.log](https://github.com/HewlettPackard/terraform-provider-oneview/files/6678436/crash.log)
[main.tf.txt](https://github.com/HewlettPackard/terraform-provider-oneview/files/6678437/main.tf.txt)
[variables.tf.txt](https://github.com/HewlettPackard/terraform-provider-oneview/files/6678438/variables.tf.txt)

**Comment by wayno123** [comment]
Hmmm. Each of those items about that are larger and bold were commented out with a "#" sign. Don't consider them as active code. Thanks.

**Comment by AsisBagga** [comment]
@wayno123 Hi, Thank you for raising this issue. We have identified the bug. We are working on it and will keep you posted on this.

**Comment by wayno123** [comment]
Thank you for the quick resolution. Is the fix available in any release yet? Can I get it?

**Comment by AsisBagga** [comment]
It will be available with OV 6.20 . The release is scheduled for mid July.

**Comment by nabhajit-ray** [comment]
Hi Wayne, We are closing this as it will be available with OV 6.2 release. Please reopen if it is still not working.
