### ISSUE TITLE
terraform init is failing

### ISSUE THREAD

**Issue by nmukkelli** [HewlettPackard/terraform-provider-oneview#346]
Hi, I'm trying to use oneview provider and I'm getting the following error when I ran 'terraform init'

Initializing the backend...

Initializing provider plugins...
- Finding hewlettpackard/oneview versions matching "6.1.0"...
2021-06-30T09:51:55.350+0930 [DEBUG] New state was assigned lineage "22de54db-796f-5c7b-24c3-cc0f32293e11"
2021-06-30T09:51:55.350+0930 [DEBUG] checking for provisioner in "."
2021-06-30T09:51:55.350+0930 [DEBUG] checking for provisioner in "/home/nmukkelli/tools/terraform"
2021-06-30T09:51:55.350+0930 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2021-06-30T09:51:55.350+0930 [WARN]  Plugin lock file .terraform/plugins/linux_amd64/lock.json failed to parse as JSON: unexpected end of JSON input
2021-06-30T09:51:55.351+0930 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2021-06-30T09:51:57.174+0930 [DEBUG] GET https://registry.terraform.io/v1/providers/hewlettpackard/oneview/versions
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hewlettpackard/oneview: no available releases match the given constraints 6.1.0
╵

$terraform version
Terraform v1.0.0
on linux_amd64

I've started with main.tf

with the following code

terraform {
  required_version = ">= 0.13"
  required_providers {
    oneview = {
      source = "HewlettPackard/oneview"
          version = "6.1.0"
    }
  }
}
provider "oneview" {
        ov_username = "myadmin"
        ov_password = "mypwd"
        ov_endpoint = "myendpoint"
        ov_sslverify = false
        ov_ifmatch = "*"
}

My proxy settings seems to be ok, when I did a curl, I got a response back ok.

curl https://registry.terraform.io/v1/providers/hewlettpackard/oneview/versions

{"id":"HewlettPackard/oneview","versions":[{"version":"1.7.0-12","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"freebsd","arch":"386"},{"os":"freebsd","arch":"amd64"},{"os":"freebsd","arch":"arm"},{"os":"freebsd","arch":"arm64"},{"os":"linux","arch":"386"},{"os":"linux","arch":"amd64"},{"os":"linux","arch":"arm"},{"os":"linux","arch":"arm64"},{"os":"windows","arch":"386"},{"os":"windows","arch":"amd64"}]},{"version":"6.0.0-12","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"freebsd","arch":"386"},{"os":"freebsd","arch":"amd64"},{"os":"freebsd","arch":"arm"},{"os":"freebsd","arch":"arm64"},{"os":"linux","arch":"386"},{"os":"linux","arch":"amd64"},{"os":"linux","arch":"arm"},{"os":"linux","arch":"arm64"},{"os":"windows","arch":"386"},{"os":"windows","arch":"amd64"}]},{"version":"6.0.0-13","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"freebsd","arch":"386"},{"os":"freebsd","arch":"amd64"},{"os":"freebsd","arch":"arm"},{"os":"freebsd","arch":"arm64"},{"os":"linux","arch":"386"},{"os":"linux","arch":"amd64"},{"os":"linux","arch":"arm"},{"os":"linux","arch":"arm64"},{"os":"windows","arch":"386"},{"os":"windows","arch":"amd64"},{"os":"windows","arch":"arm"}]},{"version":"6.1.0-13","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"freebsd","arch":"386"},{"os":"freebsd","arch":"amd64"},{"os":"freebsd","arch":"arm"},{"os":"freebsd","arch":"arm64"},{"os":"linux","arch":"386"},{"os":"linux","arch":"amd64"},{"os":"linux","arch":"arm"},{"os":"linux","arch":"arm64"},{"os":"windows","arch":"386"},{"os":"windows","arch":"amd64"},{"os":"windows","arch":"arm"}]}],"warnings":null}

am I missing anything? could you please help me out? I'm stuck and can't proceed without this.

**Comment by nabhajit-ray** [comment]
The version is not 6.1.0 but  6.1.0-13. Use the below configuration

terraform {
  required_version = ">= 0.13"
  required_providers {
    oneview = {
      source  = "hewlettpackard/oneview"
      version = "6.1.0-13"
    }
  }
}

**Comment by nmukkelli** [comment]
thank you @nabhajit-ray. It worked.
