### ISSUE TITLE
Idempotency issue in the Terraform SDK. The second "terraform apply" is modifying many resources

### ISSUE THREAD

**Issue by bigmagic** [HewlettPackard/terraform-provider-oneview#358]
Hi,

We are deploying Synergy infrastructure using OneView Terraform SDK.

Into our root module, we are creating the following resources :
- ethernet networks
- FC networks
- Logical Interconncet Group
- Enclosure Group
- Logical Enclosure
- Server Profile Template
- Server Profile 

We have successfully created the Synergy configuration (after several retry and cleanup) but when we execute the apply a second times, Terraform destroy and recreate the resources. Normally we should have no change.

Due to idempotency issue, the second execution of the terraform apply, many resources are updated or recreated or destroyed :
- LIG
- uplink sets
- SPT connections
- SP (destroyed and recreated)
...

**We can't have these resources destroyed, updated or recreated in a Production environement.**

As we have changed nothing, we should have no change.

Actually it failed with:

Note : I can't share the code on the public github but I will share it internally.

```
...
          - connections {
              - allocated_mbps    = 0 -> null
              - allocated_vfs     = 0 -> null
              - function_type     = "Ethernet" -> null
              - id                = 22 -> null
              - interconnect_port = 0 -> null
              - isolated_trunk    = false -> null
              - lag_name          = "LAG9" -> null
              - mac_type          = "Virtual" -> null
              - managed           = true -> null
              - maximum_mbps      = 0 -> null
              - name              = "CN4TUN1ICB" -> null
              - network_uri       = "/rest/ethernet-networks/ab23191d-f3f5-4886-8c85-66768b031444" -> null
              - port_id           = "Mezz 3:2-e" -> null
              - requested_mbps    = "2500" -> null

              - boot {
                  - boot_vlan_id = 0 -> null
                  - priority     = "NotBootable" -> null
                }
            }
        }
    }

Plan: 3 to add, 5 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.server_profiles.oneview_server_profile.ServerProfiles["CPBGA00HVESX000001"]: Destroying... [id=CPBGA00HVESX000001]
module.server_profiles.oneview_server_profile.ServerProfiles["CPBGA00HVESX000002"]: Destroying... [id=CPBGA00HVESX000002]
module.logical_interconnect_groups.oneview_logical_interconnect_group.LIG["LIG2VC100PAB07"]: Modifying... [id=LIG2VC100PAB07]
module.logical_interconnect_groups.oneview_logical_interconnect_group.LIG["LIG3VC100PAB07"]: Modifying... [id=LIG3VC100PAB07]
module.server_profiles.oneview_server_profile.ServerProfiles["CPBGA00HVESX000001"]: Still destroying... [id=CPBGA00HVESX000001, 10s elapsed]
module.server_profiles.oneview_server_profile.ServerProfiles["CPBGA00HVESX000002"]: Still destroying... [id=CPBGA00HVESX000002, 10s elapsed]
module.logical_interconnect_groups.oneview_logical_interconnect_group.LIG["LIG2VC100PAB07"]: Still modifying... [id=LIG2VC100PAB07, 10s elapsed]
module.logical_interconnect_groups.oneview_logical_interconnect_group.LIG["LIG3VC100PAB07"]: Still modifying... [id=LIG3VC100PAB07, 10s elapsed]
module.server_profiles.oneview_server_profile.ServerProfiles["CPBGA00HVESX000002"]: Destruction complete after 11s
module.server_profiles.oneview_server_profile.ServerProfiles["CPBGA00HVESX000001"]: Destruction complete after 11s

Error: The QoS configuration is not valid. Disabled class Class 2 must not have any ingress mapping.
Enable the traffic class and retry.

  on ../Networking/lig/main.tf line 44, in resource "oneview_logical_interconnect_group" "LIG":
  44: resource "oneview_logical_interconnect_group" "LIG" {



Error: The QoS configuration is not valid. Disabled class Class 2 must not have any ingress mapping.
Enable the traffic class and retry.

  on ../Networking/lig/main.tf line 44, in resource "oneview_logical_interconnect_group" "LIG":
  44: resource "oneview_logical_interconnect_group" "LIG" {

```

Version used:

- hewlettpackardenterprise/hpe-oneview-sdk-for-terraform:v6.2.0-13-OV6.2 :

```
bash-5.1# terraform --version
Terraform v0.13.6
+ provider registry.terraform.io/fmontezuma/restapi v1.14.1
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hewlettpackard/oneview v6.1.0-13
```

Best Regards,
Nicolas

**Comment by rismoney** [comment]
This makes me scared.  I don't understand why the idempotency issues are not the biggest concern for HPE.  I have been saying this for months.  I am planning to go to OV6.2 this month, and this downright scares me.  I have more lifecycle ignores in my code than I ever dreamt of, and it has made actually changes (beyond creation of resources) downright impossible.   The provider is very problematic in its current state.

I can't say this enough times, terraform needs to be able to be run and rerun multiple times in the same directory without anything changing between runs.   In addition, there should be no terraform directives like update patch.  tf files cannot be changed and then changed back in CI/CD pipelines and when you make a change in code, and tf applies, it has to actually change the config on Synergy, not just say it does and not.  

I'm not sure what to do.   For me the most frequent problem area is profiles.  Not sure if I should open a github issue for every issue.   I have been reaching out to our TAM, and not sure what else we should be doing.

**Comment by nabhajit-ray** [comment]
Hi Nicolas, The idempotency issues were resolved in  master, branch . Please let us know if your issues are resolved?

**Comment by nabhajit-ray** [comment]
Closing it as per last comment
