### ISSUE TITLE
LIG : Missing Downlink speed for interconnect type VC100

### ISSUE THREAD

**Issue by odesaphy** [HewlettPackard/terraform-provider-oneview#359]
When creating a LIG with VC100 interconnects you can choose a Downlink Speed : 
- 25Gb/s
- 50Gb/s (for 3 or fewer frames)

downlinkSpeedMode field in the OneView REST API

It is missing in the Terraform SDK LIG use case.

**Comment by AsisBagga** [comment]
@odesaphy Hi, This issue has been addressed and is merged to master branch. This should be available in next release. Ill proceed with closing this issue. If you have any questions then please feel free to open a new issue.
