### ISSUE TITLE
Server Profile Template / Server Profile : iLO Settings --> Cannot set iLO Hostname

### ISSUE THREAD

**Issue by odesaphy** [HewlettPackard/terraform-provider-oneview#360]
In the current implementation for the iLO Settings I can configure : 
AdministratorAccount
Directory
DirectoryGroups
KeyManager
LocalAccounts

We are missing the Hostname (with the support of the [Server Profile Name] token as a prefix)
```
"mpSettings": [
            {
                "settingType": "Hostname",
                "args": {
                    "hostName": "{serverProfileName}-ilo"
                }
            }
]
```

**Comment by yuvirani** [comment]
Hi @odesaphy, Thanks for bringing up this to our notice. We will look into this and get back with the fix.
