### ISSUE TITLE
Creation of Logical Enclosure fails when firmware parameter is added

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#361]
## Scenario/Intent

Hello, I am trying to add the firmware definition block to my code when I create a Logical Enclosure but it ends with an "400 bad request".

## Environment Details

- OneView Terraform Provider: v6.2.0-13
- OneView Appliance Version: 6.10

## Steps to Reproduce

The code was pushed on the repository we shared internally, in the logical enclosure.

## Expected Result

The command `terraform apply -var-file=variables.tfvars` creates a logical enclosure successfully.

## Actual Result
 
```
Error: Error in response: Unrecognized JSON field.
 Response Status: 400 Bad Request
 Response Details: The field named firmware near line 1, column 186 is not a valid field in this JSON object.

  on main.tf line 44, in resource "oneview_logical_enclosure" "logical-enclosures":
  44: resource "oneview_logical_enclosure" "logical-enclosures" {

```

`terraform apply -var-file=variables.tfvars`

```
  # oneview_logical_enclosure.logical-enclosures["LE1"] will be created
  + resource "oneview_logical_enclosure" "logical-enclosures" {
      + enclosure_group_uri = "/rest/enclosure-groups/f3e96a45-fcd9-4045-abdc-a81cad065713"
      + enclosure_uris      = [
          + "/rest/enclosures/0000000000A66101",
          + "/rest/enclosures/0000000000A66102",
        ]
      + id                  = (known after apply)
      + name                = "LE1"

      + firmware {
          + firmware_baseline_uri  = "/rest/firmware-drivers/Synergy_Custom_SPP_2021_02_01_Z7550-97110"
          + force_install_firmware = false
        }
    }

```

Am I declaring the firmware block in the main.tf file correctly ?

Thank you for your answer,

Claire

**Comment by nabhajit-ray** [comment]
Hi Claire,

We have added this in our backlog and woould be taken as per priority.

Closing it here
