### ISSUE TITLE
Get oneview_ipv4_range by Name

### ISSUE THREAD

**Issue by odesaphy** [HewlettPackard/terraform-provider-oneview#364]
Current implementation is to get first the Subnet Id, to get the range_uris and then get the ipv4 range by Id.

Since the ipv4 range name is unique accross all Subnet Ids, it would be great to retrieve the ipv4 range by its name

**Proposed implementation :**
```
data "oneview_ipv4_range" "iprange" {
  name = "POOLMGMT"
}
```

**Comment by nabhajit-ray** [comment]
This defect is added to our backlog and will be fixed once it is prioritized.Closing it here
