### ISSUE TITLE
Server Profiles - Terraform doesn't wait for deletion to complete

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#366]
## Scenario/Intent

When doing a terraform destroy of all ressources (from the server profiles to the networks), Terraform tries to delete the logical enclosure before the end of the server profiles deletion.

However, the output of the destroy says that the destruction of the server profiles is complete after ~10s.

In the OneView GUI, the server profiles are still in the process of being deleted but as they have multiple connections and are assigned to a server hardware, it takes more time for them to be deleted in the OneView.

## Expected Result

The server profiles are all deleted and Terraform waits for the destruction to be complete before moving to delete other objects (in our case the logical enclosure).

## Actual result

`Error: Unable to deleted this logical enclosure because it is hosting active server profiles`

**Comment by AsisBagga** [comment]
Hi @ClaireHayard Thank you for raising this issue, we will look into this.

**Comment by AsisBagga** [comment]
Hi @ClaireHayard 
As of now this fix is merged in GitHub. This fix would be available provider version 6.3.
Ill proceed with closing this issue, and if you have any concerns please feel free to open a new issue.
