### ISSUE TITLE
LIG - Need to set "desiredFecMode", improvement needed

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#371]
Hello,

For our configuration of the LIG's uplink sets, we need to set, in the logical port configs parameters, the field "desiredFecMode" (as described in the REST API).

![LIG-uplink-set-config](https://user-images.githubusercontent.com/16883146/128682446-db0cca4f-f65c-4408-ae67-93caf3939328.png)

Best regards,

Claire HAYARD

**Comment by nabhajit-ray** [comment]
Hi Claire, we will look into this.

**Comment by AsisBagga** [comment]
@ClaireHayard Hi, This issue has been addressed and is merged to master branch. This should be available in next release. Ill proceed with closing this issue. If you have any questions then please feel free to open a new issue.
