### ISSUE TITLE
Question - Is there any sample examples of HPE iLO or redfish APIs with terraform integration? 

### ISSUE THREAD

**Issue by SoibamRepo** [HewlettPackard/terraform-provider-oneview#379]
Hi, 

could you please suggest the best possible solution of HPE iLO or Redfish APIs integration with terraform ? if there are such sample examples, its would be greatfull.. 

thanks in advance.

Regards
Soibam

**Comment by chpasek** [comment]
Hi Soibam,

HPE iLO Terraform Provider is a separate project based on a different API. The HPE OneView Terraform Provider project does not and will not support such an integration. Currently, the HPE iLO Terraform Provider is still in planning. It will be released sometime in the near future in a separate repository (i.e. iLO Terraform Provider). 

Best regards, 
Christopher Pasek
HPE iLO Ecosystem Product Management

**Comment by nabhajit-ray** [comment]
Closing as per previous comment
