### ISSUE TITLE
server profile connections id

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#398]
Trying to confirm if the id field is handled properly.  If I create a set of connections and the id's are out of order. the provider looks like it ignores the id.  

  connection_settings {
    connections {
      id             = 2
      name           = "Management-02"
...
      id             = 1
      name           = "Management-01"
...
}

I believe my outputs end up like despite the id listed:
 ~ id                     = 1 -> 2

and
 ~ id                     = 2-> 1

In my actual configuration I imported, the nodes have 6 networks, where 1,2 are ethernet, 3,4 are networksets, and 5,6 are ethernet.  So I am trying to model this.

**Comment by rismoney** [comment]
This is a low priority.  I reordered the interfaces and I was able to plan/apply.

**Comment by AsisBagga** [comment]
@rismoney Hi Rich, can you please try the same with our latest version 6.3.0-13 and let us know how it goes.

**Comment by nabhajit-ray** [comment]
Hi Rismoney,

We have released another version ( 6.3.1-13) as the previous version's registry issue is still not fixed. Do let us know if you face any issue with 6.3.1-13

**Comment by rismoney** [comment]
i think we can close this.  Since I reordered the interfaces this works as expected!
Good job to all!
