### ISSUE TITLE
terraform init fails on 6.3.0-13

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#402]
```
terraform {
  required_providers {
    oneview = {
      source = "HewlettPackard/oneview"
      version = "6.3.0-13"

    }

    local = {
      source  = "hashicorp/local"
    }
  }

}
```

PS C:\gitrepos\terraform\sp_eg02> C:\terraform13\terraform.exe init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/local v2.1.0
- terraform.io/builtin/terraform is built in to Terraform
- Finding hewlettpackard/oneview versions matching "6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13, 6.3.0-13"...

Error: Failed to install provider

Error while installing hewlettpackard/oneview v6.3.0-13: could not query
provider registry for registry.terraform.io/hewlettpackard/oneview: failed to
retrieve authentication checksums for provider: 404 Not Found

**Comment by rismoney** [comment]
6.2 works, so I think something is missing on the registry

```
PS C:\gitrepos\terraform\sp_eg02> C:\terraform13\terraform.exe init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/local v2.1.0
- terraform.io/builtin/terraform is built in to Terraform
- Finding hewlettpackard/oneview versions matching "6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13, 6.2.0-13"...
- Installing hewlettpackard/oneview v6.2.0-13...
- Installed hewlettpackard/oneview v6.2.0-13 (signed by a HashiCorp partner, key ID 2A89658DFAEA93E1)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/local: version = "~> 2.1.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by rismoney** [comment]
this does not exist: 
GET https://github.com/HewlettPackard/terraform-provider-oneview/releases/download/v6.3.0-13/terraform-provider-oneview_6.3.0-13_SHA256SUMS

**Comment by rismoney** [comment]
@yuvirani

**Comment by nabhajit-ray** [comment]
This will be fixed.  Closing it here.

**Comment by nabhajit-ray** [comment]
We will be looking into this and will share once it is resolved.

**Comment by nabhajit-ray** [comment]
Hi Rismoney,

We had to release another version ( 6.3.1-13) as the previous version's registry issue is still not fixed. Do let us know if you face any issue with 6.3.1-13

**Comment by rismoney** [comment]
This is fixed! TYVM!! Great work.
