### ISSUE TITLE
iLO Local Account Permissions - Some permissions are missing

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#403]
Hello,

For our configuration of iLO in the Server Profile Template, we would like to set all permissions for the local account of a given user. As it is, we can only set the following permissions with the SDK:

![image](https://user-images.githubusercontent.com/16883146/134679198-1aaa4bbe-77bd-4c10-bdf4-89f5fb14a68f.png)

Is it possible to add them ?

Best regards,

Claire HAYARD

**Comment by nabhajit-ray** [comment]
This enhancement is added to our backlog and will be fixed once it is prioritized.Closing it here
