### ISSUE TITLE
No login permission in new iLO local account added

### ISSUE THREAD

**Issue by SoibamRepo** [HewlettPackard/terraform-provider-oneview#409]
We are trying to add new iLO local accounts through iLO settings of server profile. The accounts are created successfully but it does not have login permission. 

TF config file 
# Configure Oneview Provider
provider "oneview" {
  ov_username   = var.username
  ov_password   = var.password
  ov_endpoint   = var.endpoint
  ov_sslverify  = var.ssl_enabled
  ov_apiversion = var.api_version
  ov_ifmatch    = "*"
   ov_domain = var.ov_domain
}

# Update Server Profiles with iLO settings on DL Server
resource "oneview_server_profile" "DTAG_SP" {
  count                = length(var.server_profile_attr)
  name                 = var.server_profile_attr[count.index]["name"]
  server_hardware_type = var.server_profile_attr[count.index]["server_hardware_type"]
  hardware_name        = var.server_profile_attr[count.index]["hardware_name"]
  type                 = "ServerProfileV12"
  update_type          = "put"

  management_processor {
    manage_mp = true
    mp_settings {
      dynamic "local_accounts" {
        for_each = var.local_accounts
        content {
          display_name                 = local_accounts.value.display_name
          ilo_config_priv              = local_accounts.value.ilo_config_priv
          remote_console_priv          = local_accounts.value.remote_console_priv
          user_config_priv             = local_accounts.value.user_config_priv
          user_name                    = local_accounts.value.user_name
          virtual_media_priv           = local_accounts.value.virtual_media_priv
          virtual_power_and_reset_priv = local_accounts.value.virtual_power_and_reset_priv
          password                     = local_accounts.value.password
        }

Environment used:
DL360 Gen 10 1 
Oneview 6.3
Pull master branch and build oneview provider locally

Regards
Soibam

**Comment by AvijitOS** [comment]
Currently login specific permission attribute is not yet available in the SDK. We have added this requirement as enhancement in our backlog. For urgency and setting up priority, please reach out to our Product Management team.

**Comment by nabhajit-ray** [comment]
Closing this, as we have added this in our backlog. It will be picked as per priority.

**Comment by odesaphy** [comment]
@nabhajit-ray We also need this permission. 
By when did you plan to schedule this fix ?
For information on Synergy SY480 Gen10 all possible permissions for a local account are (the missing one in bold) : 

- userConfigPriv
- remoteConsolePriv
- virtualMediaPriv
- virtualPowerAndResetPriv
- iLOConfigPriv
- **loginPriv**
- **hostBIOSConfigPriv**
- **hostNICConfigPriv**
- **hostStorageConfigPriv**
