### ISSUE TITLE
Use firmware baseline name instead of uri - enhancement needed

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#412]
## Scenario/Intent

Hello,

I am trying to add the firmware baseline to my DLs SPT configuration. However, to add one, I have to specify the firmware baseline uri.

However it would be easier to add the firmware baseline shortname in the tfvars configuration file.

Note: I tried to use the data of the firmware drivers to get the firmware object from the OneView and from that the uri. However like the baseline uri, I don't have a way to get the id from the firmware on OneView GUI.

```
data "oneview_firmware_drivers" "drivers" {
    id = "P35939_001_gen10spp-2021_04_0-SPP2021040_2021_0409_17"
}

output "firmware_drivers_value" {
  value = data.oneview_firmware_drivers.drivers.uri
}
```

## Environment Details

- OneView Terraform SDK provider: v6.3.1-13
- OneView Appliance Version: 6.10

## Expected Enhancement

Use the firmware baseline name to configure a firmware on a DLs SPT.

```
firmware = {
  firmware_baseline_name   = "SPP 2021.04.0" #"Gen10 Service Pack for ProLiant version 2021.04.0"
  force_install_firmware   = false
  firmware_install_type    = "FirmwareOnly"
  firmware_activation_type = "Immediate"
}
```

**Comment by nabhajit-ray** [comment]
The enhancement request is added to our backlog and will be taken up as per priority. Closing it here.

**Comment by ClaireHayard** [comment]
Hello @nabhajit-ray, any news on this issue ? It seems I can't reoppen it.

**Comment by nabhajit-ray** [comment]
Hi @ClaireHayard , Please check in the master branch where this is fix is now added.

**Comment by ClaireHayard** [comment]
Hello @nabhajit-ray,

The fix you provided works. Thank you !
