### ISSUE TITLE
Server Profile - reinitilize controller is not set from Server Profile Template

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#420]
## Scenario/Intent

Hello,

When applying the Server Profile to a Server Hardware, the parameter to reinitialize the controller (`reinitialize_controller`) was not set to `true` as specified in the Server Profile Template.

## Environment Details

- OneView Terraform SDK provider: v6.3.0-13 (build manually from the master branch)
- OneView Appliance Version: 6.10

## Expected Result

The Server Profiles for the DLs takes all the parameters from the Server Profile Template it is created from.

## Actual Result

In the tfstate file, for the Server Profile:
`"initialize": false,`

In the Server Profile Template:
`"initialize": true,`

**Comment by nabhajit-ray** [comment]
As discussed this can be done with the SP configuration, can this be closed?

**Comment by nabhajit-ray** [comment]
Closing this as per last comment
