### ISSUE TITLE
Server Profile Template - Local storage import_configuration cannot be set

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#427]
## Scenario/Intent

Hello,

We have the possibility in the Server Profile Template to set the `import_configuration` parameter in the controller with the SDK. However this parameter is not setable in the GUI for a Server Profile Template. It is in the Server Profile.

I was trying to change the `import_configuration` from false to true in my SPT config as well as the `initialize_controller` from true to false. I got an error when doing the `terraform apply`.

In my tfvars, before my changes:
```
    controller = [
      {
        # Controller parameters
        device_slot              = "Embedded"
        import_configuration     = false
        reinitialize_controller  = true
```

In my tfvars, after my changes:
```
    controller = [
      {
        # Controller parameters
        device_slot              = "Embedded"
        import_configuration     = true
        reinitialize_controller  = false
```

**Note**: I also have a (maybe) related issue on the `reinitialize_controller ` (https://github.com/HewlettPackard/terraform-provider-oneview/issues/420)

## Environment Details

- OneView Terraform SDK provider: v6.3.0-13 (build manually from the master branch)
- OneView Appliance Version: 6.10

## Expected Result

Clarification on the usage of the `import_configuration` parameter. Where does this parameter has to be specified ?
If it can not be defined in the SPT configuration, it may be necessary to delete it in the SPT structure to avoid confusion.

## Actual Result

```
Error: Error in response: Unrecognized JSON field.
 Response Status: 400 Bad Request
 Response Details: The field named importConfiguration near line 1, column 1,827 is not a valid field in this JSON object.

  on ../Server_Profile_Template/main.tf line 16, in resource "oneview_server_profile_template" "ServerProfileTemplate":
  16: resource "oneview_server_profile_template" "ServerProfileTemplate" {
```

**Comment by nabhajit-ray** [comment]
As discussed this can be done with the SP configuration, can this be closed?

**Comment by ClaireHayard** [comment]
Indeed, I am doing some tests to add the local storage into the SP. However we ran into another issuedoing this because the order of creation fo the logical drives was not respected. I will be opening another issue on this.

**Comment by nabhajit-ray** [comment]
Since this can be done using SP and we already have a issue for logical drive we, closing this.
