### ISSUE TITLE
Enhancement: Add Oneview settings configuration

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#43]
Hi,

Similar to adding the notifications configuration (https://github.com/HewlettPackard/terraform-provider-oneview/issues/31), it would be great if we could also configure other settings within oneview such as the ILO ranges and network configuration.

Do we know when these additions might be added to the go-sdk so that these enhancements could be looked at.

Cheers

**Comment by nabhajit-ray** [comment]
We have added this our backlog and will be taken up as per our priority . Closing this here.
