### ISSUE TITLE
Question - Updates on Server Hardware password

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#436]
## Scenario/Intent

Hello,

I understand that we cannot change the password or username for a DL server hardware, however even if the execution of the apply ends with an error, the tfstate is changed. I would assume there is no consequences on OneView side as it does not handle updates of password.

I don't understand where this behavior is coming from. Could you shed some lights on this ?

Note: the example I give here is for the password but the behavior should be the same for the other parameters (username, password, configuration state, initial scope uri).

## Environment Details

- OneView Terraform SDK provider: v6.3.1-13 (build from master branch)
- OneView Appliance Version: 6.30

## Result

```
Error: Fields like username, password, configuration_state and initial_scope_uris cannot be changed

  on main.tf line 1, in resource "oneview_server_hardware" "ServerHardwares":
   1: resource "oneview_server_hardware" "ServerHardwares" {
```
During the terragrunt plan, Terraform does an update in place, as I changed the password value in my configuration:

```
 ~ resource "oneview_server_hardware" "ServerHardwares" {
        configuration_state      = "Managed"
        force                    = true
        [...]
      ~ password                 = (sensitive value)
        power_state              = "Off"
        [...]
    }
```

Tfstate before the apply:

```
        {
          "index_key": "<server_hostname>",
          "schema_version": 0,
          "attributes": {
            "configuration_state": "Managed",
            "force": true,
            "hostname": "<server_hostname>",
            "initial_scope_uris": [],
             [...]
            "name": "<server_hostname>",
            "one_time_boot": "Normal",
            "password": "PASSWORD",
            "power_state": "On",
            "server_group_uri": "null",
            [...]
          }
        }
```

Tfstate after the apply:
```
        {
          "index_key": "<server_hostname>",
          "schema_version": 0,
          "attributes": {
            "configuration_state": "Managed",
            "force": true,
            "hostname": "<server_hostname>",
            "initial_scope_uris": [],
             [...]
            "name": "<server_hostname>",
            "one_time_boot": "Normal",
            "password": "PASSWORDCHANGED",
            "power_state": "On",
            "server_group_uri": "null",
            [...]
          }
        }

```

**Comment by nabhajit-ray** [comment]
Hi Claire, 

We will look into this and get back to you.

**Comment by nabhajit-ray** [comment]
Password field is not stored by terraform as Oneview never returns password. To conform to idempotency, we are reading the password value from the configuration file.  When you updated the password , the operation throws an error that password can not be changed. Any change in tfstate file is because we are reading it from the configuration file and actual update did not happen

**Comment by nabhajit-ray** [comment]
Closing this as password can not be handled by terraform as it is not returned by OneView
