### ISSUE TITLE
Server Profile - Logical drives are not added in a specified order

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#438]
## Scenario/Intent

Hello,

In the context of the issues #420 AND #427, I moved the block of local storage controller from the SPT to the SP. For this controller I have 2 logical drive, one for system boot and the other for data. In our configuration, we have the system disk as the first volume and the data one as the second volume and **we need to respect this order.**

When we create the Server Profile, the order is switched.

## Environment Details

- OneView Terraform SDK provider: v6.4.0-13
- OneView Appliance Version: 6.30

## Expected Result

The Logical drives of the Server Profile controller are created in the order specified in the configuration.

In the input file:

```
      controller = [
        {
          # Controller parameters
          device_slot              = "Embedded"
          import_configuration     = false
          reinitialize_controller  = true
          [...]
          logical_drives = [
            {
              # Logical drive Boot disk options/parameter
              accelerator        = "Unmanaged"
              drive_bootable     = true
              drive_technology   = "SataSsd"
              logical_drive_name = "System"
              [...]
            },
            {
              # Logical drive Data disk options/parameter
              accelerator        = "Unmanaged"
              drive_bootable     = false
              drive_technology   = "SasSsd"
              logical_drive_name = "Data"
              [...]
            }
          ]
        }
      ]
```

## Actual Result

![image](https://user-images.githubusercontent.com/16883146/143583600-437c68d9-8e2b-45b4-a5f3-8d7453fce029.png)

**Comment by nabhajit-ray** [comment]
Hi Claire, 
Let us know if the provided pluging(sent offline) is working for you.

**Comment by ClaireHayard** [comment]
Hello @nabhajit-ray,

Do you have any upddate on this ?

**Comment by nabhajit-ray** [comment]
This is fixed in master. Please re open if it is not resolved.
https://github.com/HewlettPackard/terraform-provider-oneview/pull/456
