### ISSUE TITLE
Logical Interconnect Groups broken on C7000 with 6.3+

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#439]
It looks like Logical Interconnect Groups are broken for C7000 on 6.3 and 6.4.

The first issue is that `redundancy_type` was made a required attribute in 6.3+. This field is not used or supported with C7000, but I was able to work around it by just giving it a value of `""`.

The second issue appears to be that `port_flap_settings` is read in with a `d.Get` instead of a `d.GetOK`.  When I attempt to update a C7000 logical interconnect group, I am seeing this:

```
│ Error: PortFlapProtection is not supported for My_C7000_LIG_A. 
│ Remove PortFlapProtection parameter(s) and retry.
│ 
│   with module.my_c7000_ligs.oneview_logical_interconnect_group.ligA,
│   on .terraform/modules/my_c7000_ligs/main.tf line 1, in resource "oneview_logical_interconnect_group" "ligA":
│    1: resource "oneview_logical_interconnect_group" "ligA" {
│ 
╵
```

I do not have a `port_flap_settings` block declared in my code.

**Comment by nabhajit-ray** [comment]
We will check and get back to you.
Thanks

**Comment by nabhajit-ray** [comment]
We have added this in our backlog. Will be picking it based on priority. Closing it here.
