### ISSUE TITLE
Unable to apply server_hardware (Invalid character '.)

### ISSUE THREAD

**Issue by Schluggi** [HewlettPackard/terraform-provider-oneview#440]
Hi,

same issue as #312 but with server_hardware:

```hcl
resource "oneview_server_hardware" "test" {
  hostname = "1.2.3.4"

  username = var.ilo_username
  password = var.ilo_password

  configuration_state = "Managed"
  licensing_intent    = "OneViewNoiLO"
}
```

```tf
│ Error: unable to retrieve server hardware Error in response: Listing resources failed.
│ Unable to parse filters [name matches '', hidden=false]. Invalid character '.
│  Response Status: 400 Bad Request
│  Response Details:               
│ 
│   on test.tf line 1, in resource "oneview_server_hardware" "test":
│    1: resource "oneview_server_hardware" "test" {    
│
```

**Comment by nabhajit-ray** [comment]
Thanks for reporting this. We will get back to you on this

**Comment by nabhajit-ray** [comment]
Can you please share the full steps? We wanted to know whether you are adding the server hardare,updating existing one or importing an existing server hardware .

**Comment by Schluggi** [comment]
It's happened while adding new server hardware. So i can't test updating or removing.

**Comment by nabhajit-ray** [comment]
Hi @Schluggi , Do you see the server hardware added to your OV, although the operation itself ended in error.

If no, can you try manually adding the server hardware in the OV UI ?

We can see that we are not returning the proper error  message, but we do suspect server hardware is having issue even if done manually.

**Comment by Schluggi** [comment]
@nabhajit-ray i will check it later this week.

**Comment by nabhajit-ray** [comment]
Can you check and let us know if this still an issue?

**Comment by Schluggi** [comment]
I just checked but the error is gone. I'll comment on this issue if i can reproduce it. Thank you.
