### ISSUE TITLE
Which OneView Features not yet supported?

### ISSUE THREAD

**Issue by jdonnerstag** [HewlettPackard/terraform-provider-oneview#443]
The document says "minimal" support of OneView, and it lists the OneView Features which are supported. I would very much be interested in OneView features *not yet* supported by the Teraform provider. Does this exist anywhere?

**Comment by nabhajit-ray** [comment]
You can find the list of supported resource here

https://github.com/HewlettPackard/terraform-provider-oneview/blob/master/endpoints-support.md
