### ISSUE TITLE
FC Networks - Assign Bandwidth

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#45]
Hi,

When creating an FC Network do you know if there is currently an option to set the Preferred/Max bandwidth?

Cheers
Mark

**Comment by jsmartt** [comment]
At this time there is no option to set this via Terraform, sorry. All the available options should be documented in this repo.

**Comment by wingZero21** [comment]
Hi,

Is there any chance that this is going to be updated to allow these options to be set in the future?
