### ISSUE TITLE
Labels - Can't delete all labels assigned to a resource

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#451]
## Scenario/Intent

Hello,

I am assigning multiple labels to some resources (Server Profiles, Server Profile Templates etc.), using a dynamic block for the labels in my main.tf as well as a list of labels as input.

However, when I try to remove all labels for a given resource, Terraform does not detect any changes when I do a `terraform plan`.

## Environment Details

- OneView Terraform SDK provider: v6.5.0-13
- OneView Appliance Version: 6.30

## Expected Result

When giving a empty list of labels, all labels previously assigned to the resource are detected as changes with a `terraform plan` and then deleted after a `terraform apply`.

### input file

1. Assigning labels to a resource:

```
{
    resource_name = "sptest380"
    labels = ["test1", "test2"] => list of labels to assign to the resource
}
```

2. Removing all assigned labels:

```
{
    resource_name = "sptest380"
    labels = []
}
```

3. Result of terraform apply:

```
oneview_label.ServerProfileLabels["sptest380"]: Refreshing state...
------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

The labels previously assigned to the resource are still on OneView:
![image](https://user-images.githubusercontent.com/16883146/149785976-de0a39ac-f61e-404d-a6c1-7f395f79e158.png)

### mainf.tf

```
resource "oneview_label" "ServerProfileTemplateLabels" {
  for_each = [...]
  resource_uri = "<resource_uri>"
  dynamic "labels" {
    for_each = each.value.labels
    content {
      name = labels.value
    }
  }
}
```

**Comment by nabhajit-ray** [comment]
We will look into this and will update it here

**Comment by ClaireHayard** [comment]
Hello @nabhajit-ray, I re-tested my code with the new version of the SDK and it is now working. I am closing the issue.
