### ISSUE TITLE
profile connection server idempotentcy issue:

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#458]
6.30 
using oneview provider 6.3.1-13
plan output: ( concat'd for easy reading)

this node has 6 connections, but this is the first 1, so I am not sure why it thinks its a delete/readd.
I am putting a lifecycle ignore on connections as a temporary workaround until we can figure out why so I can continue to build profiles.

      ~ connection_settings {
            reapply_state = "NotApplying"

          - connections {
              - allocated_mbps         = 1000 -> null
              - allocated_vfs          = 24 -> null
              - function_type          = "Ethernet" -> null
              - id                     = 1 -> null
              - interconnect_port      = 0 -> null
              - interconnect_uri       = "/rest/interconnects/ea007447-19d6-4d4e-b07a-082066033ee7" -> null
              - isolated_trunk         = false -> null
              - mac_type               = "Physical" -> null
              - managed                = true -> null
              - maximum_mbps           = 10000 -> null
              - name                   = "ETH_1" -> null
              - network_uri            = "/rest/ethernet-networks/bac6358c-c64c-43f5-bcdc-0d7a1707982a" -> null
              - port_id                = "Mezz 3:1-a" -> null
              - private_vlan_port_type = "None" -> null
              - requested_mbps         = "1000" -> null
              - state                  = "Deployed" -> null
              - status                 = "OK" -> null

              - boot {
                  - boot_vlan_id       = 0 -> null
                  - ethernet_boot_type = "PXE" -> null
                  - priority           = "Primary" -> null
                }
            }

          + connections {
              + allocated_mbps         = 1000
              + allocated_vfs          = 24
              + function_type          = "Ethernet"
              + id                     = 1
              + interconnect_port      = 0
              + interconnect_uri       = "/rest/interconnects/ea007447-19d6-4d4e-b07a-082066033ee7"
              + isolated_trunk         = false
              + mac_type               = "Physical"
              + managed                = true
              + maximum_mbps           = 10000
              + name                   = "ETH_1"
              + network_uri            = "/rest/ethernet-networks/bac6358c-c64c-43f5-bcdc-0d7a1707982a"
              + port_id                = "Mezz 3:1-a"
              + private_vlan_port_type = "None"
              + requested_mbps         = "1000"
              + state                  = "Deployed"
              + status                 = "OK"

              + boot {
                  + boot_vlan_id       = 0
                  + ethernet_boot_type = "PXE"
                  + priority           = "Primary"
                }
            }
```

**Comment by nabhajit-ray** [comment]
Hi @rismoney ,

We will look into this and get back to you.

**Comment by nabhajit-ray** [comment]
Please share _terraform plan -no-color >plan.txt_

Also share your configuration file.

**Comment by nabhajit-ray** [comment]
Since, there is no reply, closing it
