### ISSUE TITLE
Error: Provider Produced Inconsistent Result After Apply

### ISSUE THREAD

**Issue by josyfj** [HewlettPackard/terraform-provider-oneview#464]
Hello,

When trying to use the "Oneview_server_profile" to apply a profile to a new server from a template, I get the following error: 

`│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.Create_Server_Profiles.oneview_server_profile.SPWithDL["172.18.31.21"], provider
│ "module.Create_Server_Profiles.provider[\"registry.terraform.io/hewlettpackard/oneview\"]" produced an unexpected new
│ value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵`

Here is the resource that I am having issues with, with the serverlist variable being a map variable with the hardware name (IP address) and hardware type as the key and value, respectively. 

resource "oneview_server_profile" "SPWithDL" {
  for_each = var.serverlist
  name                 = "${each.key} profile"
  hardware_name        = each.key
  server_hardware_type = each.value
  template = "${each.value} template"
}

The goal is to make an all-encompassing project that will add server hardware, create a profile template based on the hardware type, then apply the template to those applicable servers using the resource above. Below are my resources for adding the server hardware and creating a template, as well as my variable file: 

##Add Server Hardware##
resource "oneview_server_hardware" "sh" {
  #for_each = toset( ["172.18.31.18", "172.18.31.19", "172.18.31.20", "172.18.31.21"] )
  for_each = var.serverlist 
  configuration_state = "Managed"
  hostname            = each.key
  username            = var.svusername
  password            = var.svpassword
  licensing_intent    = "OneViewNoiLo"
  initial_scope_uris  = [data.oneview_scope.scope_obj.uri]
}

##Create Profile Template##
resource "oneview_server_profile_template" "ServerProfileTemplateWithDLServer" {
  for_each =  toset(var.templatelist)
  name                 = "${each.value} template" 
  server_hardware_type = each.key
  boot_mode {
    manage_mode     = true
    mode            = "UEFI"
    pxe_boot_policy = "Auto"
  }
}

##variable file##

`endpoint = "THIS_IS_MY_ENDPOINT"

#Oneview login
ovuser = "administrator"
ovpswd = "password"

#Server login
serveruser = "administrator"
serverpswd = "password"

#Server hardware types

serverlist = {
  "172.18.31.18" = "DL360 Gen10 1"
  "172.18.31.19" = "DL380 Gen10 1"
  "172.18.31.20" = "DL380 Gen10 1"
  "172.18.31.21" = "DL560 Gen10 1"
}

#Models of templates to create
templatelist = ["DL360 Gen10 1", "DL380 Gen10 1", "DL560 Gen10 1"]`

Thank you for any assistance!

**Comment by nabhajit-ray** [comment]
We will look into it and get back to you with our results

**Comment by josyfj** [comment]
Issue resolved, there was a problem with the variables. Thank you very much!
