### ISSUE TITLE
Oneview_Server_hardware flagging items as "change" even when consistent

### ISSUE THREAD

**Issue by josyfj** [HewlettPackard/terraform-provider-oneview#465]
When adding servers to oneview using Terraform, I have an issue where those servers will be marked for change if I try to run a terraform Plan or Apply a second time.

The resource is being run inside of a module, however I can reproduce the issue even if I isolate the resource and run it directly. 

For every already-added server I run through the Oneview_Server_hardware resource, I get the following output showing the changes:

```
  # module.Initial_Setup_Module.oneview_server_hardware.sh["172.18.31.20"] will be updated in-place
  ~ resource "oneview_server_hardware" "sh" {
        id                       = "37353738-3336-584D-5131-303430343037"
      ~ licensing_intent         = "OneViewNoiLO" -> "OneViewNoiLo"
        name                     = "172.18.31.20"
        # (18 unchanged attributes hidden)
    }
Plan: 0 to add, 6 to change, 0 to destroy.

```
The expected output is:

`Plan: 0 to add, 0 to change, 0 to destroy.`

Terraform seems to want to change the licensing_intent variable, however the variable has not changed at all. 

Attached is my resource and variable file. [add_server_hardware.zip](https://github.com/HewlettPackard/terraform-provider-oneview/files/8224570/add_server_hardware.zip)

Thank you very much for any assistance

**Comment by nabhajit-ray** [comment]
licensing intent name is changed from OneViewNoiL(O)" -> "OneViewNoiL(o)"
