### ISSUE TITLE
Assign SAN manager when adding a Fiber Channel network

### ISSUE THREAD

**Issue by josyfj** [HewlettPackard/terraform-provider-oneview#471]
When adding a Fiber Channel network using the **oneview_fc_network** resource, there doesn't seem to be a way to assign a SAN manager to the FC network. On the **oneview_fcoe_network** resource, there is an attribute for assigning a managed_san_uri, however we cannot find the same attribute for adding the SAN manager to a regular fc network. 
Is it possible to assign the SAN manager with the current resource, or is this a feature that may be added at some future point?

Below is a how we have the resource currently configured.

```
resource "oneview_fc_network" "FCNetwork" {
  for_each = var.Network-Map
  name               = each.value["name"]
  fabric_type        = each.value["fabric_type"]
  type               = each.value["type"]
  initial_scope_uris = [data.oneview_scope.scope_obj.uri]
  bandwidth {
    maximum_bandwidth = each.value["maximum_bandwidth"]
    typical_bandwidth = each.value["typical_bandwidth"]
  }
}
```

What we would like to do is incorporate the managed_san_uri attribute like this, or something similar.

```
resource "oneview_fc_network" "FCNetwork" {
  for_each = var.Network-Map
  name               = each.value["name"]
  fabric_type        = each.value["fabric_type"]
  type               = each.value["type"]
  managed_san_uri    = each.value["managed_san"]
  initial_scope_uris = [data.oneview_scope.scope_obj.uri]
  bandwidth {
    maximum_bandwidth = each.value["maximum_bandwidth"]
    typical_bandwidth = each.value["typical_bandwidth"]
  }
}
```

Could you advise whether this is possible to do currently, or if a feature like this will be made available?

**Comment by nabhajit-ray** [comment]
This is fixed in master branch closing it here.
Cofiguration example:

resource "oneview_fc_network" "FCNetwork" {
  name               = "TestFCNetworkSAN1"
  fabric_type        = "FabricAttach"
  type               = "fc-networkV4"
  managed_san_uri    =  "/rest/fc-sans/managed-sans/123"
  initial_scope_uris = [data.oneview_scope.scope_obj.uri]
  bandwidth {
    maximum_bandwidth = 10000
    typical_bandwidth = 1500
  }
}
