### ISSUE TITLE
Adding multiple networks to a network set

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#48]
Hi,

Can you advise on if it is possible to create a network set with multiple ethernet-networks?

When trying the below it seems to complain that it does not conform with the supported UUID pattern. However when creating with just the one network it seems to be created without issue.

Cheers

Details:
Error:
* oneview_network_set.default: Error in response: The identifier provided for the resource ethernet-networks does not conform with supported UUID pattern.

Working
```
resource "oneview_network_set" "default" {
  name = "multi_networkset_a"
  network_uris = ["/rest/ethernet-networks/52060138-229c-469b-adyh-953409defbfe"]
}
```
Not Working
```
resource "oneview_network_set" "default" {
  name = "multi_networkset_a"
  network_uris = ["/rest/ethernet-networks/52060138-229c-469b-addf-953407defbfe", "/rest/ethernet-networks/a7e71066-fbac-45c8-a0e6-805202823"]
}
```

**Comment by wingZero21** [comment]
Hi,

Any ideas on this? Not really sure what the problem is here as it works fine when just adding the one network set. Can you advise what might be causing this to not allow more than one network to be added?

Cheers

**Comment by jsmartt** [comment]
@wingZero21, maybe a copy-paste error? The UUIDs are different lengths, which is easier to spot when they are stacked vertically:

```
/rest/ethernet-networks/52060138-229c-469b-addf-953407defbfe
/rest/ethernet-networks/a7e71066-fbac-45c8-a0e6-805202823
```

UUIDs are typically the same length, so I believe the second one is missing a few characters

**Comment by wingZero21** [comment]
Hi,

I did notice this, however checking via the UI it does seem to be what has been assigned for some reason.

I have also tested again and it seems to be working now, however I have also added the networks to the interconnect. Do the vlans need to be on the interconnect as well before they can be added to the networkset?

Cheers

**Comment by jsmartt** [comment]
I believe networks can be added to a network set even before associating them with an interconnect. However, you wont' be able to assign either to a ServerProfile until it's added to an uplink on a Logical Interconnect associated with that HW (through the LogicalEnclosure).

**Comment by wingZero21** [comment]
Interestingly I also had to delete the networkset that it had created before it would generate it properly.

I have seen this issue occur when generating the ethernet-networks we see the below error? Do you know what might cause these to occur, this might be something for another issue.

Details:
```
1 error(s) occurred:

* oneview_network_set.default: 1 error(s) occurred:

* oneview_network_set.default: Error in response: 
 Response Status: 400 Bad Request
```

**Comment by jsmartt** [comment]
I'm not sure about that one. I'd need more details about why it was a bad request. I wonder if that's something you can get Terraform to log with a debug log level

**Comment by AsisBagga** [comment]
@wingZero21 Hi Since we havent recieved any updates from you yet, we have to proceed with closing this issue. 
You can try our latest Terraform-Oneview Version 1.5.0 which have many bug fixes and enhancements, it supports Oneview REST API Version 2000 and let us know if you still have any doubts or concerns.
