### ISSUE TITLE
Enhancement: Allow more options to be configured for server profile/template

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#49]
Hi,

It would be good if there were further options that are able to be configured via the server profiles/templates.

The important ones I can see are below.

- Disk Configuration
- Bios boot mode (Legacy bios/uefi)
- Bios options

Cheers

**Comment by 5mzJyf6m** [comment]
Please add firmware.

**Comment by soodpr** [comment]
@5mzJyf6m - Please have a look at this demo to add firmware:
https://github.com/HewlettPackard/terraform-provider-oneview/blob/a99079ca1847e0370d54407e33f93c79a4189cf2/examples/demos/infrastructure_provisioning_with_i3s.tf

**Comment by AsisBagga** [comment]
@wingZero21 - Boot mode and Bios Options exist now in newer version of Terraform Oneview API 1800. However, i am not sure what do you mean by "Disk Configuration", if you mean adding local storage, then it already exist.

PS: You can have a look at [infrastructure_provisioning_with_i3s.tf](https://github.com/HewlettPackard/terraform-provider-oneview/blob/a99079ca1847e0370d54407e33f93c79a4189cf2/examples/demos/infrastructure_provisioning_with_i3s.tf)file in demo for adding firmware, Bios Settings and Boot Mode Settings. Thanks

**Comment by AsisBagga** [comment]
Hi, Since we haven't received any updates, ill proceed with closing this issue.
If you still have any query, you can let us know by opening a new issue, we will be glad to assist. Thanks.
