### ISSUE TITLE
documentation typo

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#495]
https://github.com/HewlettPackard/terraform-provider-oneview/blob/e53ef0c32c37f72f6899e1529d1ada6fe0828e0d/docs/r/server_profile.html.markdown?plain=1#L249

I believe this should be:

Specifies the way a firmware baseline is installed.  Valid Options [FirmwareAndOSDrivers,FirmwareOnly,FirmwareOnlyOfflineMode]

**Comment by nabhajit-ray** [comment]
Yes, that is a typo . Thanks for letting us know. Will fix it.
