### ISSUE TITLE
Deploy OS' without ICSP or Image Streamer

### ISSUE THREAD

**Issue by greeneg** [HewlettPackard/terraform-provider-oneview#50]
We need more direct access to the iLO that Terraform can talk through to DL hardware

**Comment by jsmartt** [comment]
Hi @greeneg. This sounds like it may fall under a separate terraform provider for iLO, as opposed to OneView, but what sort of management/configuration were you looking for?

**Comment by AsisBagga** [comment]
@greeneg Hi Gary, we haven't received any reply from you yet on Jared's question, we would be happy to assist you on your query if you may let us know specifically what sort of configuration are you looking for?

**Comment by AsisBagga** [comment]
@greeneg Hi Gary, since we haven't received any reply yet, ill proceed with closing this issue. 
If you have any query, you may contact us by opening a new issue.
