### ISSUE TITLE
firmwareBaselineName doesn't show the actual SPP name

### ISSUE THREAD

**Issue by LahiriArindam** [HewlettPackard/terraform-provider-oneview#500]
Hello All, I am getting the firmware baseline name as Gen10 Service Pack for ProLiant  or Service Pack for ProLiant but not the actual SPP details. Is there any workaround to get the actual SPP name or version.

#----------- fw Baseline
Function Export-fwBaseline($connection, $sheetName, $destWorkbook)
{
        $valuesArray            = [System.Collections.ArrayList]::new()
        $InputObject            = get-OVbaseline -ApplianceConnection $connection

        foreach ($fwBase in $InputObject)
        {
                $fwElement                      = new-object -type firmwareBundle
                # - OV strips the dot from the ISOfilename, so we have to re-construct it
                $filename               = rebuild-fwISO -BaselineObj $fwBase
                $fwElement          = new-object -TypeName firmwareBundle
                $fwElement.name     = $fwBase.name
                $fwElement.isofile  = $filename

                $valuesArray        += $fwElement

        }
        writeto-Excel -data $ValuesArray -sheetName $sheetName -destworkBook $destWorkbook
}

Below is the OneView module details,

6.0.2785.2604        HPEOneView.600                      PSGallery            HPE OneView PowerShell Library

Thank you.

**Comment by nabhajit-ray** [comment]
Is this about PowerShell library or Terraform provider?
https://github.com/HewlettPackard/POSH-HPEOneView

**Comment by nabhajit-ray** [comment]
Closing this as did not hear from you. Please open another defect if you have any issue
