### ISSUE TITLE
Updates for OneView 6.6 LTS release?

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#507]
Since OneView 6.6 is an LTS release and supported until December 2023, would you consider making additional patch releases for that version? In other words, I am looking for a v6.6.1-13 type of release.

For example, I was able to resolve #439 myself and the fix for it is pretty small.

**Comment by adarobin** [comment]
Specifically, this is all that was needed.

https://github.com/HewlettPackard/terraform-provider-oneview/commit/de67e4c14a0e5c954b008cbd716f32f5b3beb6c5

**Comment by nabhajit-ray** [comment]
Hi @adarobin ,
We are able to reproduce the issue and working on the fix. As our SDK is back ward compatible so we are planning to make the fix in the main branch and it will available with  v8.1.0-13  release. Do let us know if you have any  queries regarding this.

**Comment by nabhajit-ray** [comment]
This is fixed in new release. closing it here

**Comment by nabhajit-ray** [comment]
This is fixed in new release. closing it here
