### ISSUE TITLE
version clarification 

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#508]
If I am on Synergy Composer Oneview 7.0 API4000 do I need to match that up with the 7.0.0-13 or should I be using a newer version of the provider?  

I am mostly managing TF profiles.  Wondering if I could/should use 7.2 or 8 to take advantage of fixes, or I am supposed to use the version in lockstep?  I wanted to make sure I don't run into bug fixes of 7.1 (ie importing profiles), etc?

**Comment by nabhajit-ray** [comment]
As our SDK is backward compatible, you can use the latest SDK version to take advantage of all the fixes.
