### ISSUE TITLE
ilo settings change in server prof template not applying properly to server profile template

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#515]
```
[2023-02-14T17:59:40.021Z] â•·
[2023-02-14T17:59:40.021Z] â”‚ Error: The iLO settings are invalid:
[2023-02-14T17:59:40.021Z] â”‚ Argument "directoryUserContext" is not allowed for iLO setting "Manage directory configuration" because it conflicts with argument "directoryAuthentication".
[2023-02-14T17:59:40.021Z] â”‚ Argument "directoryGenericLDAP" is not allowed for iLO setting "Manage directory configuration" because it conflicts with argument "directoryAuthentication".
[2023-02-14T17:59:40.021Z] â”‚ Required argument "directoryAuthentication" is missing for iLO setting "Manage directory configuration".
[2023-02-14T17:59:40.021Z] â”‚ Argument "directoryServerPort" is not allowed for iLO setting "Manage directory configuration" because it conflicts with argument "directoryAuthentication".
[2023-02-14T17:59:40.021Z] â”‚ Argument "directoryServerAddress" is not allowed for iLO setting "Manage directory configuration" because it conflicts with argument "directoryAuthentication".
[2023-02-14T17:59:40.021Z] â”‚ Required argument "password" is missing for iLO setting "Local accounts". 
[2023-02-14T17:59:40.021Z] â”‚ Correct the specified iLO settings arguments.
```

template contains:

```
management_processor {
    manage_mp = true
    mp_settings {

      local_accounts {
        user_name                    = var.iloadmin_username
        display_name                 = var.iloadmin_username
        password                     = var.iloadmin_password
        user_config_priv             = true
        remote_console_priv          = true
        virtual_media_priv           = true
        virtual_power_and_reset_priv = true
        ilo_config_priv              = true
        login_priv                   = true
        host_bios_config_priv        = true
        host_nic_config_priv         = true
        host_storage_config_priv     = true
      }

      directory {
        directory_authentication     = "defaultSchema"
        directory_generic_ldap       = false
        directory_server_address     = "server" #renamed
        directory_server_port        = 636
        directory_user_context       = ["CN=server,DC=local"]  # renamed
        kerberos_authentication      = false
      }
    }
  }

```

existing profile doesn't have any ilo settings, and then I apply a profile with these template settings and receive above error.
if i delete profile, and apply, it performs the proper configuration, but a modification of an existing profile, fails.

**Comment by nabhajit-ray** [comment]
Will check this and get back to you

**Comment by nabhajit-ray** [comment]
Hi @rismoney ,

Just wanted to get the scenario correctly. You created profile and then tried to update the profile by using new template which is having ilo settings.
Or
You created a template and trying to update he template by adding ilo settings.

**Comment by rismoney** [comment]
> Just wanted to get the scenario correctly. You created profile and then tried to update the profile by using new template which is having ilo settings.

This

**Comment by nabhajit-ray** [comment]
Hi @rismoney ,

I am using the below configuration and it is working.
To update the profile from template the update type is _patch_
```
resource "oneview_server_profile" "sp_from_spt" {
  name                 = "sp_from_spt"
  update_type = "patch"
  options {        
          op = "replace"
          path = "/templateCompliance"
          value = "Compliant"        
}
```

**Comment by rismoney** [comment]
I still don't get this.  Shouldn't terraform know how/when to use the right API call instead of me needing to know?   Do I need those options below?  Will initial profile creation work with this, meaning if I have no profile and wany to create one, will it have to be POST?   I guess I dont understand the workflow if all my server profile are created in a module. Trying to avoid code modification, and have the module just do the right thing.

**Comment by nabhajit-ray** [comment]
Hi @rismoney ,

We understood the issue and have added this to our backlog and it will be taken up as per priority.

**Comment by rismoney** [comment]
@nabhajit-ray can you re-open

If I import the profile and have a profile configured in terraform that uses ilo settings in its template, and try to change something unrelated like a network connection I get the same error. It is not clear to me, where the setting is conflicting.
I have even added management_processor to ignore_changes and that still doesn't just skip it.  I believe something else isn't right here.

Thank you for your time!

**Comment by nabhajit-ray** [comment]
Hi @rismoney , For our understanding:

In Oneview  GUI:
1. Created a template with ilo settings.
2.  Created a profile using the template from step2.
In terraform:
1. Imported the profile .
2. Changed the network connection in ( add a new connections or just editing?


Can you share the detailed steps and also the configuration file you are using for profile and template

**Comment by nabhajit-ray** [comment]
Closing it here as did not hear from you for sometime

**Comment by rismoney** [comment]
What about all the idempotency issues that were put on the backlog?  Are those going to be addressed?
Terraform should know what api calls to make without changing the code
