### ISSUE TITLE
What API Versions are supported?

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#52]
I'm seeing this when I set `ov_apiversion = 600` and try to create an ethernet network:

```
Error: Error applying plan:

1 error(s) occurred:

* oneview_ethernet_network.default: 1 error(s) occurred:

* oneview_ethernet_network.default: Error in response: The "type" field content, "ethernet-networkV3", included in this request is invalid.
 Response Status: 400 Bad Request
```

I assume this is due to the fact that the type should be `ethernet-networkV4` in the 600 API version.  What is the highest API version this provider supports currently?

**Comment by soodpr** [comment]
@adarobin - Here, the default value of type in ethernet network resource is "ethernet-networkV3" which is for API200 but i think you can overwrite type value by below code:
resource "oneview_ethernet_network" "default" {
  name = "test-ethernet-network"
  vlan_id = 71
  type = "ethernet-networkV4"
}
I have tested for FC networks for API500 and it worked.
