### ISSUE TITLE
Automated Oneview deployment

### ISSUE THREAD

**Issue by joaofeteira** [HewlettPackard/terraform-provider-oneview#545]
Hi,

I am trying to launch and e2e automated oneview VM (including configuration).
For the first step I am using the .ova file within a terraform deployment then I would want to jump directly to this provider for the configuration but it seems that I have to perform a password change of the Admin user for this provider to work (it doesn't with the default Administrator/admin credentials).
Is there any way to do it? Or do I have always to interrupt the process manually after the .ova deployment to just change the admin password and then configure it with this provider?
A possible way would be to have a vapp property on the .ova image to set a new admin password.

Thanks a lot
BR

**Comment by nabhajit-ray** [comment]
Hi @joaofeteira, thanks for  sharing the issue. Currently we do have support for change default password. Will  add this is in our backlog and it will be taken up as per priority.

**Comment by joaofeteira** [comment]
Hi @nabhajit-ray  thanks for the reply. I think it will be useful having some more properties than just the default password.
As I mentioned the goal is to have it E2E automated and by having a brief look at both the default state after the launch of the .ova and both the Terraform , Ansible and Python providers I noticed that one would eventually need the actions below to be inputted as .ova properties since they are not available on any of the providers:

- Accept the EULA and/or skip at all the configuration Wizard when we enter the appliance for the first time
- Have the possibility to activate the REST API by default with the default Admin User (or as i mentioned having the possibility to change the Admin password which seems to activate the REST API)
- Set the Appliance Hostname, IPv4, IPv6, and DNS configuration (with the possibility of having static IPs)
- Skip the Initial "Oneview Tutorial" screen
- Adding Oneview Licenses

Maybe I am missing some but it seems those are the one we need from the moment Oneview is brought up as an VMware .ova template until the moment we can start with any of the providers for its further configuration.

Thanks a lot
BR

**Comment by nabhajit-ray** [comment]
Hi @joaofeteira ,

To understand the full scenario your requirements. 
First deploy the OVA into vcenter using third party(e.g ovftool) tool and set the initial ips.

Then SDK will access the OneView using the set IP and do the following operation:
1. EULA acceptance
2. Password change
3. Remaining network configuration.
4. Add OneView license

At present we do not have the 4 mentioned operation in our SDK and we will add them to our backlog.
Thanks,

**Comment by joaofeteira** [comment]
Hi,

Sure the goal is an hands off deployment. And right now the main things that aren't allowing that are the ones I mentioned.
From my tests I think point 2. password change needs to occur in the OVA because the SDK can't connect with the default Admin Password.
Thanks
