### ISSUE TITLE
Error: The selected server hardware has health status other than "OK"

### ISSUE THREAD

**Issue by FalcoSuessgott** [HewlettPackard/terraform-provider-oneview#548]
Adding a Server Profile from a Hardware and a Server Profile Template results in:

```hcl
data "oneview_server_profile_template" "template" {
  name = "${replace(jsondecode(data.http.ilo.response_body).Product, " ", "_")}_${var.config_pattern}_${var.firmware_baseline}"
}

resource "oneview_server_profile" "this" {
  name          = var.hostname
  hardware_name = var.hostname
  server_hardware_type = data.oneview_server_profile_template.template.server_hardware_type
  template = data.oneview_server_profile_template.template.name
}
```

```
Error: The selected server hardware has health status other than "OK". 
│ Select a different server hardware with a healthy status or address the alerts on the server hardware before proceeding.
```

While I do understand the root cause is to fix the security risks on the ILO. I'm asking if there is a way to bypass risks and force the Server Profile creation?

**Comment by FalcoSuessgott** [comment]
https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/server-profiles:
>   Comma-separated list of flags for ignoring specific warnings. Calls may use "all" (or "true") to pass all ignore flags, or "none" (or "false") to pass none of them. Quotes are optional. The supported comma-separated list of flags are:
ignoreSANWarnings
When provided, the operation will ignore warnings for non-critical issues detected in the SAN storage.

I can see the resource supports a force flag provided as query. Does the provider support specifying a query?

**Comment by nabhajit-ray** [comment]
The force param is not yet supported. We will add this to our backlog and fix it as per our priority.

**Comment by FalcoSuessgott** [comment]
@nabhajit-ray Opened an MR in the underlying Go-Lib, you might take a look. Really appreciate a Review :)
