### ISSUE TITLE
Ability to provide cloud-init user data to the OS on first boot.

### ISSUE THREAD

**Issue by MnrGreg** [HewlettPackard/terraform-provider-oneview#59]
Has there been any thoughts on providing cloud-init user data to the server profile OS at initial boot up. This would help customers standardize a part of their provisioning process similar to that of their public and private cloud providers.

Of course, one can host the cloud-init user-data external the OS on an http endpoint or through removal media but was wondering if there might be a way to provide it over the synergy blade bus or ILO somehow?

**Comment by soodpr** [comment]
If you are using Synergy with Image Streamer...it should be possible to pass details through properties on the deployment plan.  Custom scripts would need to be create to take those properties and write them to a cloud-init file.

Let me know if that answers your query.

**Comment by AsisBagga** [comment]
@MnrGreg Hi, i hope your query is answered, hence will be proceeding with closing this issue. If you have any further doubts, let us know, will reopen this issue to address it.
