### ISSUE TITLE
Server Profile Template connections broken with API 500+

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#60]
API version 500 and up have a new field named `connectionSettings` that now contains the `connections` field used on the Server Profiles deployed from the template.  This makes it impossible to configure connections on server profile templates with newer API versions from Terraform.

Now that https://github.com/HewlettPackard/oneview-golang/pull/140 is merged, it should be possible to fix here.

**Comment by 5mzJyf6m** [comment]
@adarobin 
Is there a status for this issue? Using the latest version of OneView 4.2 with api version 1000. Thanks.

**Comment by adarobin** [comment]
@5mzJyf6m I don't work for HPE, but I would love to have this working in my environment too :-)

It appears that API 800 support may be added in the near future looking at #82 .  Perhaps @jyothis-gireesan can provide some insight.

**Comment by AsisBagga** [comment]
@adarobin @5mzJyf6m  
Hi,
This had been addressed for APIs grater than API 600. 
Let me know if you have any questions before we close this issue. 
Thanks.
