### ISSUE TITLE
Upgrade Terrafrom to latest stable version- 0.12.4

### ISSUE THREAD

**Issue by soodpr** [HewlettPackard/terraform-provider-oneview#62]
> 
> 
> The only thing I'm not happy with is that I need to go back and manually set `enclosure_indexes` to `[1]` for all of my C7000 enclosures. I'd like to make `[1]` the default value, but that is not possible in the version of Terraform that this plugin is linked against.

Hello @adarobin - I agree we should use latest Terraform version. May be we can take this as an enhancement in future.

_Originally posted by @soodpr in https://github.com/HewlettPackard/terraform-provider-oneview/pull/56#issuecomment-451064592_

**Comment by 5mzJyf6m** [comment]
Hi @soodpr and @madhav-bharadwaj - Is there an ETA for this enhancement? We use Terraform with other providers so would be great to move up to 0.12.x. Thank you.

**Comment by adarobin** [comment]
At this point it probably makes more sense to target the [Terraform Plugin SDK](https://www.terraform.io/docs/extend/plugin-sdk.html).

**Comment by soodpr** [comment]
> 
> 
> At this point it probably makes more sense to target the [Terraform Plugin SDK](https://www.terraform.io/docs/extend/plugin-sdk.html).

Thanks for bringing this up. I think its a great idea.

**Comment by adarobin** [comment]
It looks like the upgrade tool they recommend requires using `go mod` instead of `govendor`.  I migrated  the code base and migrated to the Terraform Plugin SDK.  The plugin still compiles successfully, but I have not done any testing.

I documented the commands I ran at each point in the commit messages https://github.com/HewlettPackard/terraform-provider-oneview/compare/master...umich-vci:upgrade_terraform

**Comment by adarobin** [comment]
I wish the Synergy Simulator was publicly available, then it would be a lot easier to run acceptance tests.

**Comment by adarobin** [comment]
Any progress on this?  Terraform 0.13 RC1 is out.

**Comment by jontyq** [comment]
We'd like to use this and keep everything Terraform, however with the state of this provider looks like we'll get shunted for standing up the Synergy piece.

Can we get some commitment to updating everything to latest?

Happy to help provide some PR's.

**Comment by adarobin** [comment]
Terraform 0.14 is out at this point

**Comment by nabhajit-ray** [comment]
We have upgraded our provider to support terraform 0.13.36. Closing this here. Please open another issue for Terraform version related issue
