### ISSUE TITLE
create util function to get scope by name while creating a resource instead of hardcoding it

### ISSUE THREAD

**Issue by soodpr** [HewlettPackard/terraform-provider-oneview#63]
just a thought...can we pass scope name here and then use GetScopesByName to get the scope in create

_Originally posted by @soodpr in https://github.com/HewlettPackard/terraform-provider-oneview/pull/61/files_

**Comment by adarobin** [comment]
It might make more sense to create a "scope" Terraform data source that lets you look up the URI and pass it along.

**Comment by AsisBagga** [comment]
This request has been implemented. Hence Closing the issue.
