### ISSUE TITLE
Cross build in Windows system 

### ISSUE THREAD

**Issue by SoibamRepo** [HewlettPackard/terraform-provider-oneview#83]
could anyone let me know the produce to build terraform-provider-oneview in Windows 10 environment ?

**Comment by AsisBagga** [comment]
@SoibamRepo Hi Soibam, just follow below steps to build the terraform-provider-oneview in windows 10 environment.
In command prompt run :-
1. go get github.com/HewlettPackard/terraform-provider-oneview  
2. cd %GOPATH%/src/github.com/HewlettPackard/terraform-provider-oneview  
3. go build -o terraform-provider-oneview  

Prerequisites: 
Install Go and terraform and make sure you have set the paths for terraform and go correctly.

**Comment by AsisBagga** [comment]
@SoibamRepo Hi I hope it helped you, Ill proceed with closing the case, if you still have any doubts, you can create a new issue, we would be glad to assist.
