### ISSUE TITLE
oneview_ethernet_network for OneView 4.2 api 1000 type parameter invalid

### ISSUE THREAD

**Issue by 5mzJyf6m** [HewlettPackard/terraform-provider-oneview#84]
Getting errors when configuring ethernet networks. When created thru the OneView GUI the network type is ethernet-networkV4. Current version of the Terraform provider defaults to ethernet-networkV3 and uses API version 800. Using terraform provider, ethernet-network, ethernet-networkV3, or ethernet-networkV4 were not accepted. 

Using the API worked with "ethernet-network" but not V3 or V4 to update an existing network.
Creating a network using the API works with "ethernet-networkV4". 

The terraform configs and the errors are below. Using OneView 4.20 with api version 1000 and Terraform v0.11.13. 

resource "oneview_ethernet_network" "devops-220" {
  name          = "devops-220"
  vlan_id       = 220
  smart_link    = "true"
  type          = "ethernet-network"
  purpose       = "devops-deployments"
}

* oneview_ethernet_network.devops-220: Error in response: Invalid JSON type.
 Response Status: 400 Bad Request
 Response Details: The "type" field content, "ethernet-network", included in this request is invalid.

**Comment by jyothis-gireesan** [comment]
Please try with type value changed to **_ethernet-networkV4_** which is the type value needed for v1000.

**Comment by 5mzJyf6m** [comment]
@jyothis-gireesan Yes, ethernet-network, ethernet-networkV3, and ethernet-networkV4 were not accepted.

**Comment by jyothis-gireesan** [comment]
Is it throwing the same error when you use the other types as well.

**Comment by jyothis-gireesan** [comment]
Please note the purpose field you have assigned is invalid.


The values for the purpose field should be one of the following 

- **FaultTolerance** For fault tolerance purposes 
- **General** For general purposes 
- **ISCSI** iSCSI capability Management For management purposes 
- **VMMigration** For VM migration purposes

and also the **_smart_link_** field is a boolean and boolean value should not be in quotes.

So with the change use the below request:

resource "oneview_ethernet_network" "devops-220" {
name = "devops-220"
vlan_id = 220
smart_link = true
type = "ethernet-networkV4"
purpose = "General"
}

**Comment by 5mzJyf6m** [comment]
Thank you kindly. I see that info is referenced in the API documentation. 
That changed the response to "A network with the name devops-220 already exists." I was able to delete the network and use terraform to create successfully using ethernet-networkV4.
