### ISSUE TITLE
Terraform provider support for OneView 4.2 with API version 1000 needed.

### ISSUE THREAD

**Issue by 5mzJyf6m** [HewlettPackard/terraform-provider-oneview#85]
Currently the terraform provider supports OneView 4.1 with API version 800. Can this be updated? Thank you.

**Comment by jyothis-gireesan** [comment]
The update for version OneView 4.1 with API version 800 will be released soon.

Can you please specify your extra requirement needed.

**Comment by 5mzJyf6m** [comment]
We are using Oneview 4.2 and the API version is 1000. Is the current version of this provider compatible? If not, will the update provide API 1000 support? Thank you.

**Comment by 5mzJyf6m** [comment]
Hi @jyothis-gireesan @Sowmyahsg - Is there an ETA for this update?

**Comment by AsisBagga** [comment]
Hi @5mzJyf6m - API Version 1000 was on 4 Dec 2019 and Oneview 5.3 with API 1800 is recently released as well. 
Let us know if you have any other query before we close this issue.

**Comment by AsisBagga** [comment]
Hi, Since we haven't heard back from you, will close this issue. 
If you have any concerns you may open a new issue. Thank you.
