### ISSUE TITLE
Download and build from different branch , not from master

### ISSUE THREAD

**Issue by SoibamRepo** [HewlettPackard/terraform-provider-oneview#86]
Below command will download  source code from master branch only

$ go get -u github.com/HewlettPackard/terraform-provider-oneview

To download and build from branch “server_profile”,  what parameters/options do I need to pass in above commands ?  

Current code from master branch does support only "ServerProfile5"., not other Server profile types. The codes  from "server_profile" branch seems it support ServerProfile9 .. 

We have Oneview 4.0 version and synergy frame 

Regards
Soibam

**Comment by madhav-bharadwaj** [comment]
Hi @SoibamRepo, You can follow the below steps:
1. Checkout to a new branch in the local repo
2. Pull that particular branch(server profile) using the `git pull` command to your local repo
3. Execute your code on that branch.

**Comment by SoibamRepo** [comment]
> Hi @SoibamRepo, You can follow the below steps:
> 
> 1. Checkout to a new branch in the local repo
> 2. Pull that particular branch(server profile) using the `git pull` command.
> 3. Execute your code on that branch.

After pull from branch "server_profile", I check if  corrects are downloaded 
[root@localhost terraform-provider-oneview]# vim examples/
enclosure.tf        fc_network.tf       scope.tf            server_hardware.tf  server_profile.tf
[root@localhost terraform-provider-oneview]# vim examples/

Then I run below command  and got below error message 

root@localhost terraform-provider-oneview]# go get -u github.com/HewlettPackard/terraform-provider-oneview
package github.com/HewlettPackard/terraform-provider-oneview: directory "/usr/local/go/src/github.com/HewlettPackard/terraform-provider-oneview" is not using a known version control system

**Comment by madhav-bharadwaj** [comment]
There is no necessity to run `go get`. You can add your code to create the server profile(or edit the existing example file), then run the `go build` command. This would build the terraform provider with the updated code containing support for api800.
Then you can continue with the terraform operations. (init, plan , apply etc)

**Comment by SoibamRepo** [comment]
Updated server_hardware.tf and run as below 

[root@localhost terraform-provider-oneview]# go build
# _/root/server_profile/terraform-provider-oneview
./main.go:21:3: cannot use oneview.Provider (type func() "github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value
[root@localhost terraform-provider-oneview]#

**Comment by madhav-bharadwaj** [comment]
Can you please use the below command:
`go build –o terraform-provider-oneview`

**Comment by SoibamRepo** [comment]
[root@localhost terraform-provider-oneview]# go build -o terraform-provider-oneview
# _/root/server_profile/terraform-provider-oneview
./main.go:21:3: cannot use oneview.Provider (type func() "github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value
[root@localhost terraform-provider-oneview]#

**Comment by SoibamRepo** [comment]
here is terraform configuration for creating server profile using existing server profile template 

api_version = 600
resource "oneview_server_profile" "default" {
  name = "terraform-server-profile"
  hardware_name = "SGH831YR9H,bay 11"
  type = "ServerProfileV8"
  template = "ESXi-6.5-ServerProfileTemplate"
}
Error message:

1 error occurred:
        * oneview_server_profile.default: 1 error occurred:
        * oneview_server_profile.default: The value specified for the server hardware type null is not valid or not supported.
Verify parameters and try again.

**Comment by madhav-bharadwaj** [comment]
Hi @SoibamRepo , I am able to create a server profile with the attributes which you are using. Can you please check the configuration of your server profile template? Is the hardware type properly configured there?

**Comment by SoibamRepo** [comment]
![Capture](https://user-images.githubusercontent.com/26687825/58150947-d787b300-7c85-11e9-923a-f93dc75d477f.PNG)

**Comment by SoibamRepo** [comment]
The issue is resolved.

**Comment by madhav-bharadwaj** [comment]
Just for the record: The code handling the logic for SPT was commented out and was causing the problem. There is no issue as such with the existing code and the server profile create works just fine.

**Comment by SoibamRepo** [comment]
Below terraform configuration for creating server profile in Synergy frame works fine in OV 4.2. 

resource "oneview_server_profile" "default" {
  name = "terraform-server-profile"
  hardware_name = "SGH831YR9H,bay 11"
  # hardware_name = "SGH817YECA, bay 10"
  type = "ServerProfileV8"
  template = "ESXi-6.5 _Server_Profile_Template"
}

the same template config file gives error message in OV 4.00
1 error occurred:
        * oneview_server_profile.default: 1 error occurred:
        * oneview_server_profile.default: The value specified for the server hardware type null is not valid or not supported.
Verify parameters and try again.

**Comment by madhav-bharadwaj** [comment]
> 
> 
> Hi @SoibamRepo, You can follow the below steps:
> 
>     1. Checkout to a new branch in the local repo
> 
>     2. Pull that particular branch(server profile) using the `git pull` command.
> 
>     3. Execute your code on that branch.

Hi @SoibamRepo, I'm closing this issue as you are able to run the server profile code from branch. Please raise a new issue with all the details, so that we can track it better.
