### ISSUE TITLE
Fails to create server profile in OV 4.00

### ISSUE THREAD

**Issue by SoibamRepo** [HewlettPackard/terraform-provider-oneview#88]
Below terraform configuration for creating server profile in Synergy frame works fine in OV 4.2.

resource "oneview_server_profile" "default" {
name = "terraform-server-profile"
hardware_name = "SGH831YR9H,bay 11"

hardware_name = "SGH817YECA, bay 10"
type = "ServerProfileV8"
template = "ESXi-6.5 _Server_Profile_Template"
}

the same config file gives error message in OV 4.00
1 error occurred:
* oneview_server_profile.default: 1 error occurred:
* oneview_server_profile.default: The value specified for the server hardware type null is not valid or not supported.
Verify parameters and try again.

**Comment by madhav-bharadwaj** [comment]
Are we giving 2 hardware names as part of the config?

**Comment by SoibamRepo** [comment]
> Are we giving 2 hardware names as part of the config?

No .. I am giving only 1

**Comment by madhav-bharadwaj** [comment]
I see 2 hardware names in your config file above.

**Comment by madhav-bharadwaj** [comment]
Thanks for sharing the config files. I'm able to create the server profile on my oneview4.0 appliance with the same config. Can you please check if you are sending the right request body. You can get it through the vendor files as we discussed.

**Comment by SoibamRepo** [comment]
could you please share codes to  set hardware type URI  in resource_server_profile.go ? Its last option we have

**Comment by madhav-bharadwaj** [comment]
Closing this issue as the working code in the server profile branch resolves the issue. Please note that server profile creation without i3s is supported now,
